### ISSUE TITLE
Maven 1.3.0 - Eclipse issues

### ISSUE THREAD

**Issue by Rojmanning** [TIBCOSoftware/bw6-plugin-maven#109]
Maven Plugin version: 1.3.0
Maven version: 3.3.9
Product : TIBCO ActiveMatrix Businessworks 6 
Product version: 6.3.3 HF2 & 6.4.1 HF1
Component: Maven Eclipse Plugin 

If I create a fresh workspace, new application and try to "Generate POM file For Application" I receive the following error

```
java.lang.NoClassDefFoundError: com/tibco/bw/design/external/dependencies/BWExternalDependenciesHelper
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.buildModules(BWProjectBuilder.java:202)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.build(BWProjectBuilder.java:61)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:71)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

If I import an existing application that has already been set to a maven nature I cannot build the workspace as I receive the following error, tried new workspace/ existing workspace.

```

Errors occurred during the build.
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.common'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.savingsAccount.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.reference.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.mortgageApplication.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.document.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.mortgageAccount.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
Errors running builder 'BusinessWorks Project Validation Builder' on project 'sbs.bw.core.customer.interface'.
com/tibco/bw/design/external/dependencies/BWExternalDependenciesRegistry
```

If I reinstall the 1.2.2 plugin then all is okay again.
Please advise, thanks.

**Comment by Rvelamia** [comment]
Hi @Rojmanning, Maven Plugin 1.3.0 is supported starting from BusinessWorks 6.4.2. Please test it there.

**Comment by Rojmanning** [comment]
Hi, Thanks for the quick response. Will see about getting the latest BW version installed to test it out.
