### ISSUE TITLE
[question] How to export a Shared Module as jar to be imported on another Workspace?

### ISSUE THREAD

**Issue by Strickmabil** [TIBCOSoftware/bw6-plugin-maven#130]
Maven Plugin version: 1.3.0

Maven version: 3.2.3

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.4.2

Component: Maven Eclipse Plugin

I'm trying to access a Shared Module (MNLog) without importing it in my workspace (WNPlayground) as you mention in wiki link:
https://github.com/TIBCOSoftware/bw6-plugin-maven/wiki/SharedModule

Although, I'm failing on step#2 since the imported jar is labeled as a Maven Dependency under my Application (ANPlayground) and not as an independent Shared Module.

![anplayground](https://user-images.githubusercontent.com/26774462/35583380-ab19b534-05e9-11e8-8053-72d695a2a734.png)

How should I correctly export my Shared Module as jar to my local mvn repository?
This is my current configuration:
![mnlog](https://user-images.githubusercontent.com/26774462/35583425-cbfd7696-05e9-11e8-88ba-0bf8d527ac2d.png)

Thanks in advance,

VM

**Comment by Strickmabil** [comment]
Apparently I was importing the dependencies on the wrong POM (was doing it on the Application pom when I was supposed to do it on the Module one). But when I save my pom with these dependencies I'm now getting this error:
![err](https://user-images.githubusercontent.com/26774462/35731677-8419c2a4-080e-11e8-8376-5641d4cedab9.png)

On eclipse Error Log I get:
java.lang.RuntimeException: java.lang.NullPointerException
	at com.tibco.zion.project.filsystem.zip.ZipFileSystem.getStore(ZipFileSystem.java:70)
	at org.eclipse.core.internal.filesystem.InternalFileSystemCore.getStore(InternalFileSystemCore.java:107)
	at org.eclipse.core.filesystem.EFS.getStore(EFS.java:478)
	at org.eclipse.jdt.internal.core.util.Util.toLocalFile(Util.java:2416)
	at org.eclipse.jdt.internal.core.JavaProject.readFileEntriesWithException(JavaProject.java:2475)
	at org.eclipse.jdt.internal.core.JavaModelManager$PerProjectInfo.readAndCacheClasspath(JavaModelManager.java:1263)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2853)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1962)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.getRootInfos(DeltaProcessingState.java:311)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.initializeRoots(DeltaProcessingState.java:256)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2120)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:477)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:291)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:285)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:149)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:364)
	at org.eclipse.core.internal.resources.Workspace.aboutToBuild(Workspace.java:302)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:608)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
	at org.eclipse.core.internal.resources.Project.build(Project.java:114)
	at com.tibco.bw.studio.maven.validation.BWMavenValidationJob.run(BWMavenValidationJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NullPointerException
	at com.tibco.zion.project.filesystem.zip.internal.ZipItem.getItem(ZipItem.java:23)
	at com.tibco.zion.project.filsystem.zip.ZipFileStore.<init>(ZipFileStore.java:69)
	at com.tibco.zion.project.filsystem.zip.ZipFileSystem.getStore(ZipFileSystem.java:65)
	... 23 more

Any idea on what may be happening?

****

**Comment by Strickmabil** [comment]
I managed to solve this by reinstalling BW.

**Comment by Goldy7788** [comment]
I am also facing the exact same issue and reinstalling BW also doesn't help. 

Could anyone give any pointer how to resolve this?
