### ISSUE TITLE
Correct way to build an .ear using Maven Plugin

### ISSUE THREAD

**Issue by Strickmabil** [TIBCOSoftware/bw6-plugin-maven#136]
Maven Plugin version: 1.3.1

Maven version: 3.5.2

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.4.2

Component: Maven build plugin

What is the most correct way to build an .ear using Maven?
I used to 'mvn package' on the parent pom.xml project directory and everything worked as intended after deployed it on TEA except I wasn't able to see the "Process Diagram" of my deployed processes.

Doing a 'mvn com.tibco.plugins:bw6-maven-plugin:bwear' on the same directory I get a NullPointerException:

[INFO] BWEARPackager Mojo started ...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] APlayground.parent ................................. FAILURE [  0.764 s]
[INFO] MPlayground ........................................ SKIPPED
[INFO] APlayground ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.243 s
[INFO] Finished at: 2018-03-15T18:21:52+00:00
[INFO] Final Memory: 12M/158M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.3.1:bwear (default-cli) on project APlayground.parent: Failed to create BW EAR Archive: NullPointerException ->
[Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.3.1:bwear (default-cli) on project APlayground.parent: Failed to
 create BW EAR Archive
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create BW EAR Archive
        at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute(BWEARPackagerMojo.java:117)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.tibco.bw.maven.plugin.osgi.helpers.ManifestWriter.updateManifestVersion(ManifestWriter.java:37)
        at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute(BWEARPackagerMojo.java:106)
        ... 21 more

I've tried this on 2 different machines and I got the same result.
I'm currently using bwdesign system:export do generate my .ears.

**Comment by awagle** [comment]
Please have a look at #78 to generate process diagrams in Studio before building the EAR file.
