### ISSUE TITLE
POM Generation UI doesn't open

### ISSUE THREAD

**Issue by loreCande81** [TIBCOSoftware/bw6-plugin-maven#162]
Maven Plugin version: 1.3.1

Maven version: 3.5.4

Product : TIBCO Businessworks Container edition

Product version: 2.3.0

Component:  Maven build plugin 1.3.1

OS Centos 7

**Steps to reproduce the issue:**
1. Maven 3.5.4 installation performed successfully
2. TIBCO Businessworks Container edition installed successfully
3. bw6 maven plugin 1.3.1 installation performed successfully
4. When we click on Generate POM for Application, the POM generation UI doesn't open and no error messages pops up

**Comment by racheliurui** [comment]
Same issue with one of the project (tibco.bw.sample.biding.rest.basic.application), then try to convert another project then the UI showed up but the ear built out is just 4kb which contains almost nothing.

We are using 
* bw 6.4.2
* Maven 3.5.4
* Windows 10

**Comment by sonalshingavi** [comment]
@racheliurui  From where do you build EAR, Application or Parent? it should be from Parent.

**Comment by loreCande81** [comment]
Hi,
thanks for the reply. The issue has been fixed by installing the latest version of Tibco BW CE.
Thank you

**Comment by racheliurui** [comment]
Hi, all, thanks for all the support. I have fixed the issue, but summarise here just in case someone have similar issue, please consider to update the readme with more details about the tibco home variable. 

1)	During installation , it will ask for tibco home, Default is c:\tibco
•	For linux my installation on linux is /opt/tibco/bw/bw/6.4 , so initially I have used /opt/tibco, which should be /opt/tibco/bw (then the script will pick up correct version and path)
•	For windows, my %BW_HOME% is set to C:\tibco\bw\6.4 
2)	My BW is installed using sudo , the plugin installation script must have access to the tibco folder.   
•	either run using sudo and set same JAVA_HOME and M2_HOME or
•	run using plugin installation but give current user access to tibco folder

**Comment by smwatage** [comment]
> Hi @loreCande81
> Can you please share me the log file present in your workspace on path: workspace - .metadata - log.txt file.
> Thank you.

Hi Sonal.

I am using TIBCO BWCE 2.4.0
installed BW MAven plugin 1.3.1

I can see generate pom option. but on click window is not opening. Logs in .matainf and log file below

!ENTRY org.eclipse.ui 4 0 2019-02-10 18:21:17.843
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject
	at com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:33)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:75)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.ClassNotFoundException: com.tibco.zion.project.core.ContainerPreferenceProject cannot be found by bw6.studio.maven.plugin_1.3.1.201801292109
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

Thanks,
Sangamesh

**Comment by loreCande81** [comment]
It is already fixed. Thanks Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [TIBCOSoftware/bw6-plugin-maven] POM Generation UI doesn't open (#162)Da: smwatage A: TIBCOSoftware/bw6-plugin-maven CC: loreCande81 ,Mention 
Hi @loreCande81
Can you please share me the log file present in your workspace on path: workspace - .metadata - log.txt file.
Thank you.

Hi Sonal.
I am using TIBCO BWCE 2.4.0
installed BW MAven plugin 1.3.1
I can see generate pom option. but on click window is not opening. Logs in .matainf and log file below
!ENTRY org.eclipse.ui 4 0 2019-02-10 18:21:17.843
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject
at com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:33)
at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)
at org.eclipse.jface.window.Window.create(Window.java:435)
at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)
at org.eclipse.jface.window.Window.open(Window.java:797)
at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:75)
at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.ClassNotFoundException: com.tibco.zion.project.core.ContainerPreferenceProject cannot be found by bw6.studio.maven.plugin_1.3.1.201801292109
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 36 more
Thanks,
Sangamesh

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/TIBCOSoftware/bw6-plugin-maven","title":"TIBCOSoftware/bw6-plugin-maven","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/TIBCOSoftware/bw6-plugin-maven"}},"updates":{"snippets":[{"icon":"PERSON","message":"@smwatage in #162: \u003e Hi @loreCande81\r\n\u003e Can you please share me the log file present in your workspace on path: workspace - .metadata - log.txt file.\r\n\u003e Thank you.\r\n\r\nHi Sonal.\r\n\r\nI am using TIBCO BWCE 2.4.0\r\ninstalled BW MAven plugin 1.3.1\r\n\r\nI can see generate pom option. but on click window is not opening. Logs in .matainf and log file below\r\n\r\n!ENTRY org.eclipse.ui 4 0 2019-02-10 18:21:17.843\r\n!MESSAGE Unhandled event loop exception\r\n!STACK 0\r\njava.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject\r\n\tat com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:33)\r\n\tat org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)\r\n\tat org.eclipse.jface.window.Window.create(Window.java:435)\r\n\tat org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)\r\n\tat org.eclipse.jface.window.Window.open(Window.java:797)\r\n\tat com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:75)\r\n\tat org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)\r\n\tat org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)\r\n\tat org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)\r\n\tat org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)\r\n\tat org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)\r\n\tat org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)\r\n\tat org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)\r\n\tat org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)\r\n\tat org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)\r\n\tat org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)\r\n\tat org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)\r\n\tat org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)\r\n\tat org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)\r\n\tat org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)\r\n\tat org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)\r\n\tat org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)\r\n\tat org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)\r\n\tat org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)\r\n\tat org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)\r\n\tat org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)\r\n\tat org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)\r\n\tat org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)\r\n\tat org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)\r\n\tat org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)\r\n\tat org.eclipse.equinox.launcher.Main.run(Main.java:1465)\r\nCaused by: java.lang.ClassNotFoundException: com.tibco.zion.project.core.ContainerPreferenceProject cannot be found by bw6.studio.maven.plugin_1.3.1.201801292109\r\n\tat org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)\r\n\tat org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)\r\n\tat org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)\r\n\tat org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)\r\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\r\n\t... 36 more\r\n\r\nThanks,\r\nSangamesh"}],"action":{"name":"View Issue","url":"https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/162#issuecomment-462131346"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/162#issuecomment-462131346",
"url": "https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/162#issuecomment-462131346",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
