### ISSUE TITLE
Serialization error executing bwdeploy from BW application module

### ISSUE THREAD

**Issue by galvanni** [TIBCOSoftware/bw6-plugin-maven#21]
Getting the following error while attempting to deploy an ear that had already been built using mvn clean install in the context of a BW application module.

Executed mvn bw6-tc-maven-plugin:bwdeploy from the BW application module directory. 

Windows 7 
Java 1.8.0_91
Maven 3.3.9
BW 6.3.2
TEA 2.0.0 HF003

[INFO] --- bw6-tc-maven-plugin:1.1.1-SNAPSHOT:bwdeploy (default-cli) @ if-database-event-generator-application ---
[INFO] BWEAR Deployer Mojo started ...
[INFO] Deployment Config File found. Loading configuration from the same
[INFO] Connected to BWAgent. Agents found
[INFO] Agent Name -> A5CG5521C9F
[INFO] Domain exists with Name -> Provider_Manager
[INFO] AppSpace exists with Name -> Integration_Framework in Domain -> Provider_Manager
[INFO] AppNode exists with Name -> IF_NODE_1 in Domain -> Provider_Manager and in AppSpace -> Integration_Framework
[INFO] AppNode HTTP Port  -> 8060. AppNode OSGi Port -> 8008
[INFO] AppSpace is Running.
[INFO] Application exists with name -> if-database-event-generator.application. Undeploying the Application as Redeploy
flag is true.
[INFO] Uploading the Archive file -> if-database-event-generator-application_1.0.0.qualifier.ear
[INFO] Deploying the Application with name -> if-database-event-generator.application with Profile -> default.substvar
[ERROR]
com.tibco.bw.maven.plugin.admin.client.ClientException: Error reading entity from input stream. (500)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getConnectionException(RemoteDeployer.java:59)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.deployApplication(RemoteDeployer.java:524)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:259)
        at com.tibco.bw.maven.plugin.application.BWEARDeployerMojo.execute(BWEARDeployerMojo.java:152)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: javax.ws.rs.ProcessingException: Error reading entity from input stream.
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:867)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:786)
        at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
        at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
        at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
        at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.deployApplication(RemoteDeployer.java:519)
        ... 24 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "message" (class com.tib
co.bw.maven.plugin.admin.dto.Application), not marked as ignorable (21 known properties: "profileContentRef", "archivePa
th", "deploymentStatusDetail", "name", "archiveName", "domainName", "appSpaceName", "archiveRef", "ref", "profileName",
"configuration", "docURL", "version", "revision", "description", "appInstances", "instances", "state", "deploymentStatus
", "processes", "components"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@52d6d273; line: 1, c
olumn: 13](through reference chain: com.tibco.bw.maven.plugin.admin.dto.Application["message"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:836)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:135
2)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330
)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1470)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:912)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(Read
erInterceptorExecutor.java:256)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(Read
erInterceptorExecutor.java:235)
        at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:852)
        ... 34 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by galvanni** [comment]
Update:  This is a very misleading error.  The root cause of this was the application not deploying properly.  When I looked at the agent logs the standard OSGi missing dependency failure was witnessed.  So basically when the deployment goes bad - a bad response is sent back to the plugin.

**Comment by awagle** [comment]
@RajibBiswasTibco we need to have better error handling here.

**Comment by RajibBiswasTibco** [comment]
Hi @galvanni , 
From where did you get the goal 'bwdeploy' ? In the bw6-maven-plugin, there is no goal called 'bwdeploy'. Can you provide the steps to reproduce this issue?

**Comment by rahulkamdar** [comment]
No response for a month now, closing the issue since it looks like an unavailable goal was used. Please re-open if that's not the case.
