### ISSUE TITLE
MessageBodyReader not found for media type=text/html when "Run As>Maven install"

### ISSUE THREAD

**Issue by emcap** [TIBCOSoftware/bw6-plugin-maven#250]
Maven Plugin version:  2.1.1

Maven version: 3.6.0

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.5

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1. Import tibco.bw.sample.binding.rest.Basic sample project to studio, having previously installed Maving Plugin version 2.1.1 
2. Right click on "tibco.bw.sample.binding.rest.Basic.application" and click on "Generate POM for Application"
3. Configure "Maven Configuration Details for Plugin code... screen as shown ![gp4a1](https://user-images.githubusercontent.com/47567674/52784534-55b43800-304d-11e9-8211-be74ef2a69c5.png)
Click Next.
4. Configure "Deployment Details... screen as shown in the attached gp4a2.png.
![gp4a2](https://user-images.githubusercontent.com/47567674/52784652-bba0bf80-304d-11e9-94e8-ef419dca838f.png)
Click Finish.
5. Right click "tibco.bw.sample.binding.rest.Basic.application.parent" and choose "Run As>Maven install"

**Additional environment details if any:**

**Describe the results you received:**
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  1.607 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  8.729 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... FAILURE [  2.248 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.899 s
[INFO] Finished at: 2019-02-14T10:59:35+00:00
[INFO] Final Memory: 23M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.1.1:bwinstall (default-bwinstall) on project tibco.bw.sample.binding.rest.Basic.application: **Failed to deploy BW Application: MessageBodyReader not found for media type=text/html**, type=interface java.util.List, genericType=java.util.List<com.tibco.bw.maven.plugin.admin.dto.Agent>. -> [Help 1]

See the entire output below.

**Describe the results you expected:**
I expected output to be similar to the below SUCCESS output, with the resultant EAR file imported and deployed in the domain specified in the POM.xml.

[INFO] Reactor Summary for tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  1.280 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  6.646 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... SUCCESS [  3.644 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS 
[INFO] ------------------------------------------------------------------------

**Additional information you deem important (e.g. issue happens only occasionally):**
I suspect it might be a configuration issue, but I'm at lost what exactly.
I've attached a [debug.output.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/2864785/debug.output.txt) generated using mvn -X.

Console screen output:
```
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent
[INFO] tibco.bw.sample.binding.rest.Basic
[INFO] tibco.bw.sample.binding.rest.Basic.application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application.parent ---
[INFO] Installing C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application.parent\pom.xml to C:\Users\emcap\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application.parent\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwmodule (default-bwmodule) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Module Packager Mojo started for Module tibco.bw.sample.binding.rest.Basic ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.0.0.201902141059 for Maven version of 1.0.0.201902141059
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201902141059.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201902141059.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ tibco.bw.sample.binding.rest.Basic ---
[INFO] Installing C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\target\tibco.bw.sample.binding.rest.Basic_1.0.0.201902141059.jar to C:\Users\emcap\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.jar
[INFO] Installing C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic\pom.xml to C:\Users\emcap\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tibco.bw.sample.binding.rest.Basic.application 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ tibco.bw.sample.binding.rest.Basic.application ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] No sources to compile
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwtest (default-bwtest) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] -------------------------------------------------------
[INFO] Provided TibcoHome directory is invalid. Skipping Test Phase.
[INFO] -------------------------------------------------------
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwear (default-bwear) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEARPackager Mojo started ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.0.0.201902141059 for Maven version of 1.0.0.201902141059
[INFO] Adding Modules to the EAR file
[INFO] Adding Module JAR with name tibco.bw.sample.binding.rest.Basic_1.0.0.201902141059.jar with version 1.0.0.201902141059
[INFO] Adding EAR Information to the EAR File
[INFO] Manifest updated with Version 1.0.0.201902141059
[INFO] The EAR file name for Application is C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] Building jar: C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-install-plugin:3.0.0-M1:install (default-install) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] Installing C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\target\tibco.bw.sample.binding.rest.Basic.application_1.0.0.ear to C:\Users\emcap\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.ear
[INFO] Installing C:\samples\AppSpace\binding\rest\Basic\tibco.bw.sample.binding.rest.Basic.application\pom.xml to C:\Users\emcap\.m2\repository\com\tibco\bw\tibco.bw.sample.binding.rest.Basic.application\1.0.0-SNAPSHOT\tibco.bw.sample.binding.rest.Basic.application-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- bw6-maven-plugin:2.1.1:bwinstall (default-bwinstall) @ tibco.bw.sample.binding.rest.Basic.application ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: MessageBodyReader not found for media type=text/html, type=interface java.util.List, genericType=java.util.List<com.tibco.bw.maven.plugin.admin.dto.Agent>. (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getConnectionException(RemoteDeployer.java:561)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getAgentInfo(RemoteDeployer.java:141)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:159)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=text/html, type=interface java.util.List, genericType=java.util.List<com.tibco.bw.maven.plugin.admin.dto.Agent>.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:232)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:156)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:812)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:126)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:123)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.getAgentInfo(RemoteDeployer.java:138)
	... 23 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] tibco.bw.sample.binding.rest.Basic.application.parent SUCCESS [  1.607 s]
[INFO] tibco.bw.sample.binding.rest.Basic ................. SUCCESS [  8.729 s]
[INFO] tibco.bw.sample.binding.rest.Basic.application ..... FAILURE [  2.248 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.899 s
[INFO] Finished at: 2019-02-14T10:59:35+00:00
[INFO] Final Memory: 23M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.1.1:bwinstall (default-bwinstall) on project tibco.bw.sample.binding.rest.Basic.application: Failed to deploy BW Application: MessageBodyReader not found for media type=text/html, type=interface java.util.List, genericType=java.util.List<com.tibco.bw.maven.plugin.admin.dto.Agent>. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tibco.bw.sample.binding.rest.Basic.application
```

**Comment by emcap** [comment]
The Agent Port was incorrectly configured. Once the configuration was corrected, the goal was successfully executed, thought the error message could have been more helpful.
