### ISSUE TITLE
Question: Using mvn test simulating in eclipse

### ISSUE THREAD

**Issue by jwerginz** [TIBCOSoftware/bw6-plugin-maven#251]
I am interested in using the unit testing part of the plugin outside of maven.  when I run mvn test from command line it works.  When I try and duplicate what it is trying to do in eclipse I get an error:

[info] line 14:08:45,853 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@76c52298 - Registering current configuration as safe fallback point
[info] line 
...[info] line 14:08:50.885 INFO  [main] com.tibco.thor.frwk - TIBCO ActiveMatrix BusinessWorks version 6.5.0, build V63, 2018-08-08
.[info] line !SESSION 2019-02-25 14:08:33.901 -----------------------------------------------
[info] line eclipse.buildId=unknown
[info] line java.version=1.8.0_144
[info] line java.vendor=Oracle Corporation
[info] line BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
[info] line Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog -clean
[info] line 
[info] line !ENTRY com.tibco.neo.eclipse.support.osgi 4 0 2019-02-25 14:08:52.059
[info] line !MESSAGE FrameworkEvent ERROR
[info] line !STACK 0
[info] line org.osgi.framework.BundleException: Exception in com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start() of bundle com.tibco.neo.eclipse.support.osgi.
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
[info] line 	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
[info] line 	at org.eclipse.osgi.container.Module.start(Module.java:439)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
[info] line 	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
[info] line 	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
[info] line 	at org.eclipse.osgi.container.Module.start(Module.java:439)
[info] line 	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
[info] line 	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
[info] line 	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
[info] line 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
[info] line 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] line 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] line 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] line 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] line 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
[info] line 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
[info] line 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
[info] line 	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
[info] line Caused by: java.lang.IllegalArgumentException: TIBCO-AMX-INFRA-002000: invalid null value
[info] line 	at com.tibco.neo.model.types.ComponentID.<init>(ComponentID.java:31)
[info] line 	at com.tibco.neo.component.osgi.BundleMapKey.<init>(BundleMapKey.java:27)
[info] line 	at com.tibco.neo.component.osgi.OSGiEMFPackageRegistryManager.init(OSGiEMFPackageRegistryManager.java:139)
[info] line 	at com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start(NeoOSGiBundleActivator.java:67)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
[info] line 	at java.security.AccessController.doPrivileged(Native Method)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
[info] line 	... 25 more
[info] line Root exception:
[info] line java.lang.IllegalArgumentException: TIBCO-AMX-INFRA-002000: invalid null value
[info] line 	at com.tibco.neo.model.types.ComponentID.<init>(ComponentID.java:31)
[info] line 	at com.tibco.neo.component.osgi.BundleMapKey.<init>(BundleMapKey.java:27)
[info] line 	at com.tibco.neo.component.osgi.OSGiEMFPackageRegistryManager.init(OSGiEMFPackageRegistryManager.java:139)
[info] line 	at com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start(NeoOSGiBundleActivator.java:67)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
[info] line 	at java.security.AccessController.doPrivileged(Native Method)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
[info] line 	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
[info] line 	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
[info] line 	at org.eclipse.osgi.container.Module.start(Module.java:439)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
[info] line 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
[info] line 	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
[info] line 	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
[info] line 	at org.eclipse.osgi.container.Module.start(Module.java:439)
[info] line 	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
[info] line 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
[info] line 	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
[info] line 	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
[info] line 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
[info] line 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info] line 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info] line 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info] line 	at java.lang.reflect.Method.invoke(Method.java:498)
[info] line 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
[info] line 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
[info] line 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
[info] line 	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by jwerginz** [comment]
Ok Im further along.  Now it just hangs - I got rid of the error:
...[info] line 14:11:43.050 INFO  [main] com.tibco.thor.frwk - TIBCO ActiveMatrix BusinessWorks version 6.5.0, build V63, 2018-08-08
.............[info] line 14:12:02.733 INFO  [main] com.tibco.bw.frwk.engine.BWEngine - TIBCO-BW-FRWK-300002: BW Engine [Main] started successfully.
[info] line 14:12:02.756 INFO  [main] com.tibco.thor.frwk.Deployer - Started by BusinessStudio.
........[info] line 14:12:14.379 INFO  [Framework Event Dispatcher: Equinox Container: a0864853-fa39-0019-15ab-914c0c910958] com.tibco.thor.frwk.Deployer - TIBCO-THOR-FRWK-300001: Started OSGi Framework of AppNode [BWEclipseAppNode] in AppSpace [BWEclipseAppSpace] of Domain [BWEclipseDomain]
....................................................................................................................................................................................................................................................................

This is what mvn test shows:
....17:59:32.005 INFO  [main] com.tibco.thor.frwk - TIBCO ActiveMatrix BusinessWorks version 6.5.0, build V63, 2018-08-08
........17:59:44.181 INFO  [main] com.tibco.thor.frwk.Deployer - Started by BusinessStudio.
.......17:59:55.485 INFO  [main] com.tibco.bw.frwk.engine.BWEngine - TIBCO-BW-FRWK-300002: BW Engine [Main] started successfully.
.....18:00:01.804 INFO  [Framework Event Dispatcher: Equinox Container: a0f64cfc-5039-0019-1b28-cb858fc411cc] com.tibco.thor.frwk.Deployer - TIBCO-THOR-FRWK-300001: Started OSGi Framework of AppNode [BWEclipseAppNode] in AppSpace [BWEclipseAppSpace] of Domain [BWEclipseDomain]
**18:00:01.872 INFO  [Framework Event Dispatcher: Equinox Container: a0f64cfc-5039-0019-1b28-cb858fc411cc] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300018: Deploying BW Application [demo.application:1.0].**  **It is not doing this from my eclipse**
...18:00:06.915 INFO  [Framework Event Dispatcher: Equinox Container: a0f64cfc-5039-0019-1b28-cb858fc411cc] com.tibco.thor.frwk.Application - TIBCO-THOR-FRWK-300021: All Application dependencies are resolved for Application [demo.application:1.0]

**Comment by jwerginz** [comment]
Past other issues now have issue here:
BWTestRunner init():
this.r = this.jerseyClient.target(UriBuilder.fromPath(CONTEXT_ROOT).scheme(this.scheme).host(this.host).port(this.port).build());

[info] Begin BWTestRunner2 init()  
[info] jerseyClient.getConfiguration()  org.glassfish.jersey.client.ClientConfig@ffbb496b
[info] this.jerseyClient  org.glassfish.jersey.client.JerseyClient@19dc67c2
[info] CONTEXT_ROOT  /bwut
[info] this.scheme  http
[info] this.host  localhost
[info] this.port  8090
Feb 26, 2019 6:10:39 PM org.glassfish.hk2.internal.ServiceLocatorFactoryImpl getGenerator
WARNING: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
[info] End getInputRunnable run()
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
	at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:148)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.init(BWTestRunner2.java:76)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.runTestsPerModule(BWTestRunner2.java:119)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.runTests(BWTestRunner2.java:97)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor2.runTests(BWTestExecutor2.java:81)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor2.execute(BWTestExecutor2.java:28)
	at com.tibco.bw.maven.plugin.test.BWTestMojo2.execute(BWTestMojo2.java:203)
	at com.tibco.bw.maven.plugin.test.CallBWTestMojo.main(CallBWTestMojo.java:16)
Caused by: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:121)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
	... 10 more
Caused by: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:266)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:247)
	at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
	at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
	at org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:117)
	... 12 more
org.apache.maven.plugin.MojoExecutionException: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at com.tibco.bw.maven.plugin.test.BWTestMojo2.execute(BWTestMojo2.java:224)
	at com.tibco.bw.maven.plugin.test.CallBWTestMojo.main(CallBWTestMojo.java:16)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
	at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
	at javax.ws.rs.core.UriBuilder.newInstance(UriBuilder.java:95)
	at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:148)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.init(BWTestRunner2.java:76)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.runTestsPerModule(BWTestRunner2.java:119)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner2.runTests(BWTestRunner2.java:97)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor2.runTests(BWTestExecutor2.java:81)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor2.execute(BWTestExecutor2.java:28)
	at com.tibco.bw.maven.plugin.test.BWTestMojo2.execute(BWTestMojo2.java:203)
	... 1 more
Caused by: java.lang.ClassNotFoundException: Provider org.glassfish.jersey.internal.RuntimeDelegateImpl could not be instantiated: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:121)
	at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:207)
	at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
	... 10 more
Caused by: java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:266)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:247)
	at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
	at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:109)
	at org.glassfish.jersey.internal.RuntimeDelegateImpl.<init>(RuntimeDelegateImpl.java:63)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:117)
	... 12 more

**Comment by jwerginz** [comment]
I got it working - results are similar in eclipse as they are with mvn test.  Had to add a bunch of jars for the runtime execution that were already in .m2.

**Comment by shahenshaikh** [comment]
@jwerginz could you please help with the details what you actually did to get it running.
I am also getting the same issue while running test cases
