### ISSUE TITLE
BW6.3.3 project Maven deployment issue

### ISSUE THREAD

**Issue by JaganChinthakayala** [TIBCOSoftware/bw6-plugin-maven#28]
Hi Folks,

I have installed the Maven plugin for BW 6.3.3 using the instructions from https://github.com/TIBCOSoftware/bw6-plugin-maven

I have also installed TEA, started it, registered bwagent and created domain POC_Domain and Appspaces and AppNodes.

I created a test project with Greetings Web service. I am able to deploy to the domain from the eclipse after configuring the deployment servers for my BWMetaspace and POC_Domain. 

Now the issue is with deploying using Maven.

I have converted the project to a Maven project and generated POM also.

While generating the POM, it has asked me for the Domain Details and I have provided my local domain and BW agent details. All these are in the POM.xml

When I do a maven install, it is failing with the following error. It is able to generate the ear but unable to upload and deploy the same to the domain.

[ERROR] 

com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-THOR-FRWK-CMN-500000: java.lang.IllegalArgumentException: invalid version "null": non-numeric "null" (400)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:530)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:301)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:171)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[Test_Maven_Deployment.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/450120/Test_Maven_Deployment.zip)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by suneelyaram** [comment]
Hi Jagan, Have you found some solution for this problem?

**Comment by wbuczak** [comment]
Hi
We have observed a very similar issue with our TIBCO BW project(s) (created under Tibco BW 6.3.3.) When building the project with maven, the produced application EAR file does not contain the module jar inside. It only contains the META-INF folder. 

Builds seem to be working fine for projects created under previous version of the BW studio (6.3.2).  
A guess:  might that have something to do with the format change of the TIBCO.xml file, between the two versions ?

**Comment by HiteshNembhwani** [comment]
Isn't this what we were discussing here
<https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/29#issuecomment-245700935>
?

I tried with the sample app and EAR was generated properly with the jar
file. The resources folder was missing the diagram files but this is an
expected behavior. I've attached the project with pom files on the same
thread, could you verify it and see it your's is any different?

I'm assuming you're triggering the package goal from parent pom.

**Comment by awagle** [comment]
Re-open if issue is not resolved. Closing based on @HiteshNembhwani  's comment.
