### ISSUE TITLE
jaxb-api library missing

### ISSUE THREAD

**Issue by AntAreS24** [TIBCOSoftware/bw6-plugin-maven#369]
Maven Plugin version: `2.3.1`
Maven version: `3.5.4`
Product : `TIBCO Businessworks Container edition`
Product version: `2.4.5`
Component: `Maven build plugin`
**Steps to reproduce the issue:**
1. on a **build server** (works fine on local machine), BWCE installed, Maven plugin NOT installed, but jar available through Nexus.
2. In parent folder, execute `mvn clean site package`
3. Build seems to be successful, but error creating report
4. Issue doesn't occur with `mvn clean package` only

**Describe the results you received:**
```
...
[INFO] --- bw6-maven-plugin:2.3.1:bwtest (default-bwtest) @ projectest ---
[INFO] -------------------------------------------------------
[INFO] No BWT Test files exist. 
[INFO] -------------------------------------------------------
[INFO] -------------------------------------------------------
[INFO] No Tests found in any Module. Skipping Test Phase.
[INFO] -------------------------------------------------------
[INFO] 
[INFO] <<< bw6-maven-plugin:2.3.1:bwreport < [bwtestreport]test @ projectest <<<
[INFO] 
[INFO] '[bwtestreport]test' forked phase execution for bw6-maven-plugin:bwreport report preparation done
[INFO] 1 report detected for bw6-maven-plugin:2.3.1: bwreport
[WARNING] Report plugin org.apache.maven.plugins:maven-project-info-reports-plugin has an empty version.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:3.0.0
[INFO] 15 reports detected for maven-project-info-reports-plugin:3.0.0: ci-management, dependencies, dependency-info, dependency-management, distribution-management, index, issue-management, licenses, mailing-lists, modules, plugin-management, plugins, scm, summary, team
[INFO] Rendering site with default locale English (en)
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering content with org.apache.maven.skins:maven-default-skin:jar:1.2 skin.
[INFO] Generating "bwtest" report        --- bw6-maven-plugin:2.3.1:bwreport
javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:455)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at com.tibco.bw.maven.plugin.test.report.BWTestsReport.loadTestSuite(BWTestsReport.java:139)
	at com.tibco.bw.maven.plugin.test.report.BWTestsReport.executeReport(BWTestsReport.java:114)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
	... 32 more
java.lang.NullPointerException
	at com.tibco.bw.maven.plugin.test.coverage.ProcessCoverageParser.loadCoverage(ProcessCoverageParser.java:40)
	at com.tibco.bw.maven.plugin.test.report.CodeCoverageReportGenerator.generateReport(CodeCoverageReportGenerator.java:39)
	at com.tibco.bw.maven.plugin.test.report.BWTestsReport.generateCodeCoverageReport(BWTestsReport.java:78)
	at com.tibco.bw.maven.plugin.test.report.BWTestsReport.executeReport(BWTestsReport.java:117)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:251)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:230)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:349)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:198)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:147)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] projectest.parent 1.0.0-SNAPSHOT SUCCESS [  1.597 s]
[INFO] projectest.module ............ SUCCESS [  1.754 s]
[INFO] projectest 1.0.0-SNAPSHOT .... FAILURE [  0.450 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.280 s
[INFO] Finished at: 2019-09-30T14:10:35+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site (default-site) on projectprojectest: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site failed.: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :projectest
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by SujataDarekar** [comment]
@AntAreS24 Is there any test file present in the "Test" folder? Also the dependency because of which it is failing is already added in Maven Installer's POM file. Can you please check whether it is present on your Nexus repo?

**Comment by AntAreS24** [comment]
@SujataDarekar , yes there is only 1 test in the folder. I'm not sure about Nexus. I'll check tomorrow.

**Comment by AntAreS24** [comment]
@SujataDarekar I've check out Nexus and the library it NOT available. I've asked the team that looks after it and they said it's simply setup as a mirror/cache. So if the maven requests it, it will download it.

**Comment by AntAreS24** [comment]
Ok, I think I identified the issue.

I need Java 13 in my environment to run Java project, but TIBCO needs Java 8.

I could get around this by running the following command:
```
JAVA_HOME=$TIBCO_HOME/tibcojre64/1.8.0 mvn test
```
