### ISSUE TITLE
unit test - http 500- error

### ISSUE THREAD

**Issue by singhr6** [TIBCOSoftware/bw6-plugin-maven#431]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

Maven Plugin version:2.3.1

Maven version: 3.6.3

Product : TIBCO ActiveMatrix Businessworks 6 

Product version: 6.5.1 HF2

Component: Either of Maven Eclipse Plugin or Maven build plugin

maven test

**Steps to reproduce the issue:**
1. Run the bw code with  maven test goal
2. 
3.

**Additional environment details if any:**

**Describe the results you received:**
I am getting below error

[INFO] ----BW Engine Logs End---------------------------------------------------------------------------------------------------------------------------------------------------
[INFO] ## Running Test for zb-bw6x-unittest.module1.bwt ##
[INFO] Starting Tests in Module : zb-bw6x-unittest.module
[INFO] Uploading tests for Processes in Module :  zb-bw6x-unittest.module
 zb-bw6x-unittest.module.SubProcess
javax.ws.rs.InternalServerErrorException: HTTP 500 Server Error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] zb-bw6x-unittest.parent ............................ SUCCESS [  0.004 s]
[INFO] zb-bw6x-unittest.module ............................ SUCCESS [  2.775 s]
[INFO] zb-bw6x-unittest ................................... FAILURE [ 30.553 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.241 s
[INFO] Finished at: 2020-04-09T08:38:53-04:00
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTestsPerModule(BWTestRunner.java:122)
	at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTests(BWTestRunner.java:86)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.runTests(BWTestExecutor.java:110)
	at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.execute(BWTestExecutor.java:36)
	at com.tibco.bw.maven.plugin.test.BWTestMojo.execute(BWTestMojo.java:66)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Final Memory: 22M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.3.1:bwtest (default-bwtest) on project zb-bw6x-unittest: HTTP 500 Server Error -> [Help 1]
[ERROR] 

**Describe the results you expected:**
I expected the result of unit test result with no of test, failed, passed count

**Additional information you deem important (e.g. issue happens only occasionally):**
I have not been able to run the unit test via maven so far. I am able to run the unit test using business studio debug option.

I also tried to use BW 6.6 version with latest bw6 plugin version available 2.6.0 - I am still getting same error. 

project code is attached. 

[bw6x-unittest.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4456160/bw6x-unittest.zip)

**Comment by SujataDarekar** [comment]
@singhr6 Can you try to regenerate the test file again. because the test file present in Test folder of attached project is not generated correctly. The tag  <Lang>urn:oasis:names:tc:wsbpel:2.0:sublang:xslt1.0</Lang> is missing in your test file causing an issue to run test goal

**Comment by singhr6** [comment]
@SujataDarekar thank you , I am able to invoke the maven test goals.
