### ISSUE TITLE
Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.6.0:bwdeployer 

### ISSUE THREAD

**Issue by TLNarayanaRao** [TIBCOSoftware/bw6-plugin-maven#466]
Maven Plugin version: 2.6.0

Maven version: 3.3.9

Product : Either of TIBCO ActiveMatrix Businessworks 6 

Product version: 6.6.0

Component:  Maven build plugin

**Steps to reproduce the issue:**
1. Use goal as com.tibco.plugins:bw6-maven-plugin:2.6.0:bwdeployer

**Additional environment details if any:**
Linux

**Describe the results you received:**
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.6.0:bwdeployer (default-cli) on project petm-associate-SAP-ESB-sys.application: Failed to deploy BW Application: NullPointerException

**Describe the results you expected:**
It should deploy the EAR

**Complete Error **

+ cd /home/jenkins/workspace/ToolsAtmn/tibcopoc/petm-associate-SAP-ESB-sys/petm-associate-SAP-ESB-sys.application
+ /opt/maven/bin/mvn com.tibco.plugins:bw6-maven-plugin:bwdeployer -DearLocation=/tmp/petm-associate-SAP-ESB-sys.application_1.0.14.ear -Dprofile=DEV.substvar -Dbackup=false -DagentPort=8079 -DagentAuth=BASIC -DagentHost=pho-tbcapp-d03.ssg.petsmart.com -DosgiPort=9700 -Dredeploy=true -DagentPassword=admin -DagentSSL=false -DagentUsername=admin -Ddomain=BW6-DEV2 -DappSdeployToAdminpace=true -DappSpace=as-hr-msg0 -DappNode=an-hr-msg-pho-tbcapp-d03 -DhttpPort=9232
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] 'profiles.profile[artifactory].repositories.repository.id' must be unique but found duplicate repository with id central @ /home/jenkins/.m2/settings.xml
[WARNING] 'profiles.profile[artifactory].repositories.repository.id' must be unique but found duplicate repository with id snapshots @ /home/jenkins/.m2/settings.xml
[WARNING] 
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building petm-associate-SAP-ESB-sys.application 1.0.16-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- bw6-maven-plugin:2.6.0:bwdeployer (default-cli) @ petm-associate-SAP-ESB-sys.application ---
[INFO] BW Deployer Mojo started
[ERROR] 
java.lang.NullPointerException
	at com.tibco.bw.maven.plugin.application.BWDeployMojo.execute(BWDeployMojo.java:119)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.772 s
[INFO] Finished at: 2020-06-15T14:18:25-07:00
[INFO] Final Memory: 22M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.6.0:bwdeployer (default-cli) on project petm-associate-SAP-ESB-sys.application: Failed to deploy BW Application: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens always.

**Comment by awagle** [comment]
Please attach a sample project with which we can reproduce the issue.

**Comment by TLNarayanaRao** [comment]
Please find the attached projects and framework and config file we are using for deployer command. 

[petm-common-logging-exception.shared-1.0.2.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4914942/petm-common-logging-exception.shared-1.0.2.zip)
[petm-associate-SAP-ESB-sys-Develop.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4914952/petm-associate-SAP-ESB-sys-Develop.zip)
[configFile.txt](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/4914960/configFile.txt)

**Comment by vpawar-ai** [comment]
@TLNarayanaRao The **earLocation** parameter should be the path to the directory containing ear file. Please try using -

`-DearLocation=/tmp/`

It will use the first ear file available from the specified location.

**Comment by TLNarayanaRao** [comment]
Hello Vishal,

Yes, we have provided the -DearLocation in the command line as a parameter when we execute. 

Here is the complete command we are using... 

/opt/maven/bin/mvn com.tibco.plugins:bw6-maven-plugin:2.6.0:bwdeployer -DearLocation="target/petm-associate-SAP-ESB-sys.application_1.0.18.ear" -DdeploymentConfigfile="configFile.txt" -X

Please let me know if you need further information.

**Comment by vpawar-ai** [comment]
Hi @TLNarayanaRao ,

The **-DearLocation** should be path of the directory(excluding ear file name). Example - 
if your ear is located at "/home/jenkins/workspace/myapp/target/myapp.ear" then use "-DearLocation=/home/jenkins/workspace/myapp/target/"
