### ISSUE TITLE
Null Pointer Exception when Generating POM for application

### ISSUE THREAD

**Issue by brew42** [TIBCOSoftware/bw6-plugin-maven#494]
Tibco Bw 6.6.1 tested on mac and windows
Tibco TIB_BW_Maven_Plugin_2.7.0

Steps
Installed tibco bw and plugin
Open Eclipse Studio, select project, right click and select Generate POM for Application
Nothing happens

Looking at workspace logs shows stack trace below.

!ENTRY com.tibco.bw.studio.maven.plugin 4 0 2020-08-25 11:49:59.413
!MESSAGE Failed to generate the POM file 
!STACK 0
java.lang.NullPointerException
	at com.tibco.bw.studio.maven.helpers.ManifestParser.parseManifest(ManifestParser.java:26)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.buildModules(BWProjectBuilder.java:243)
	at com.tibco.bw.studio.maven.modules.BWProjectBuilder.build(BWProjectBuilder.java:66)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:72)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4188)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1467)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1490)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1475)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1279)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4031)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by vpawar-ai** [comment]
Hi @brew42 Please attach project to reproduce the issue. Thanks.

**Comment by brew42** [comment]
[ManageCustomer.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5123299/ManageCustomer.zip)

**Comment by vpawar-ai** [comment]
The zip contains only application project. Application module projects are missing.

**Comment by vpawar-ai** [comment]
Hi @brew42 Please make sure the application module and all shared modules dependencies are present in the workspace while launching generate POM file wizard. I temporarily removed the missing dependencies and was able to launch the wizard.
![image](https://user-images.githubusercontent.com/29373785/91277184-1ddc9380-e7a0-11ea-81ac-9495e7928573.png)

**Comment by brew42** [comment]
Thanks @vpawar-ai I've got it generating pom.xml and generating the ear file.

However, on extracting the ear file its missing resources.
See file listing below for pom generated ear and ear file created from 'Generate Enterprise Ear'

--File list from Ear built from pom
META-INF/
META-INF/MANIFEST.MF
META-INF/UAT02.substvar
META-INF/UAT03.substvar
META-INF/PREPROD01.substvar
META-INF/PROD02.substvar
META-INF/UAT05.substvar
META-INF/UAT04.substvar
META-INF/PRODMIRROR.substvar
META-INF/UAT01.substvar
META-INF/TIBCO.xml
META-INF/default.substvar
META-INF/PROD01.substvar
META-INF/UAT06.substvar
META-INF/maven/
META-INF/maven/com.tibco.bw/
META-INF/maven/com.tibco.bw/ManageCustomer/
META-INF/maven/com.tibco.bw/ManageCustomer/pom.xml
META-INF/maven/com.tibco.bw/ManageCustomer/pom.properties

--File listing from ear create from Generate Enterprise Ear
META-INF/MANIFEST.MF
resources/
resources/LIB_TSUTIL_SystemErrorHandler_Client/
resources/LIB_TSUTIL_SystemErrorHandler_Client/diagrams/
resources/LIB_TSUTIL_SystemErrorHandler_Client/diagrams/services.ts.util.systemerrorhandler.sub.CreateExceptionEvent.bwd
resources/LIB_TSUTIL_SystemErrorHandler_Client/diagrams/services.ts.util.systemerrorhandler.sub.SendExceptionEvent.bwd
resources/LIB_TSUTIL_SystemAudit_Client/
resources/LIB_TSUTIL_SystemAudit_Client/diagrams/
resources/LIB_TSUTIL_SystemAudit_Client/diagrams/services.ts.util.systemaudit.sub.SystemAudit.bwd
resources/ManageCustomer.module/
resources/ManageCustomer.module/diagrams/
resources/ManageCustomer.module/diagrams/Services.Common.Customer.Sub.ProcessCustomerCall.bwd
resources/ManageCustomer.module/diagrams/Services.Common.Customer.Sub.GetCustomerNotes.bwd
resources/ManageCustomer.module/diagrams/Services.Common.Customer.ManageCustomer.bwd
resources/ManageCustomer.module/diagrams/Services.Common.Customer.Sub.GetTenure.bwd
resources/ManageCustomer.module/diagrams/Services.Common.Customer.Sub.GetRescue.bwd
resources/LIB_Utilities/
resources/LIB_Utilities/diagrams/
resources/LIB_Utilities/diagrams/Utilities.DataValidator.Sub.ManageDataValidation.bwd
resources/LIB_Utilities/diagrams/Utilities.ErrorCode.Sub.ManageErrorCode.bwd
resources/LIB_Utilities/diagrams/Utilities.DataMapper.Sub.ManageMapper.bwd
LIB_Utilities_1.0.0.20200826105634.jar
ManageCustomer.module_1.0.4.20200826105634.jar
LIB_TSUTIL_SystemAudit_Client_1.0.0.20200826105634.jar
LIB_Schemas_1.0.1.20200826105634.jar
LIB_Resources_1.0.0.20200826105634.jar
LIB_TSUTIL_SystemErrorHandler_Client_1.0.0.20200826105634.jar
META-INF/UAT02.substvar
META-INF/UAT03.substvar
META-INF/PREPROD01.substvar
META-INF/PROD02.substvar
META-INF/UAT05.substvar
META-INF/UAT04.substvar
META-INF/PRODMIRROR.substvar
META-INF/UAT01.substvar
META-INF/TIBCO.xml
META-INF/default.substvar
META-INF/PROD01.substvar
META-INF/UAT06.substvar

**Comment by vpawar-ai** [comment]
Hi @brew42 Please add all shared modules in "ManageCustomer.parent\pom.xml" file. Please arrange the shared modules list  keeping dependent one's to the bottom.
```xml
 <modules>    
    <module>../LIB_TSUTIL_SystemAudit_Client</module>
    <module>../LIB_Schemas</module>
    <module>../LIB_Resources</module>
    <module>../LIB_TSUTIL_SystemErrorHandler_Client</module>
    <module>../LIB_TSUTIL_SystemAudit_Client</module>
    <module>../LIB_Utilities</module>
    <module>../ManageCustomer.module</module>
    <module>../ManageCustomer</module>
  </modules>
```
