### ISSUE TITLE
Bug with BW6.3.2 HF2

### ISSUE THREAD

**Issue by John-Zg** [TIBCOSoftware/bw6-plugin-maven#50]
Hi there, 

we try to use the plugin together with Jenkins for our CI environment. The BW version we use is 6.3.2 HF2. 
Everything works just fine, but when trying to upload the EAR file into the AppNode we get an error. This was reported to Tibco Enterprise support. They suggested to place the issue here in Github. 
The error message is:
`
.........
[INFO] AppSpace is Running.
[INFO] Uploading the Archive file -> BW_Resolve_MasterCrewData_v1_1.12.0.ear
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-THOR-FRWK-CMN-500000: java.lang.IllegalArgumentException: invalid version "null": non-numeric "null" (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:348)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:205)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:134)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:69)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-THOR-FRWK-CMN-500000: java.lang.IllegalArgumentException: invalid version "null": non-numeric "null" (400)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:543)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:342)
	... 34 more`

Is there any solution for that issue?

**Comment by rahulkamdar** [comment]
Please generate the EAR from %%bw.applicaiton%%.parent pom.xml file.

**Comment by John-Zg** [comment]
Now I get another problem. Perhaps you can help with that as well.
`[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.tibco.bw:BW_Shared_CLE_v1:0.5.0-SNAPSHOT (/home/tibco/.jenkins/jobs/xyz/BW_Shared_CLE_v1/pom.xml) has 1 error
[ERROR]     Unknown packaging: bwmodule @ line 14, column 14`

So there is a problem with one of the shared modules. It seems that the plugin does not understand the package "bwmodule"?

**Comment by rahulkamdar** [comment]
Thanks for the update! Can you please also share a full log from your Jenkins job? Or run the command with -X to generate additional logging?

**Comment by John-Zg** [comment]
Sure:
`Building in workspace /home/tibco/.jenkins/jobs/IF34/workspace
Fetching changes from the remote Git repository
Checking out Revision aed74f71905bcf8466cf26ea6a17fc574b9a9e16 (refs/remotes/origin/feature/JenkinsTest)
Parsing POMs
Found a module with path ..\..\..\SharedModules\SharedModule_CLE\Source_Code\BW_Shared_CLE_v1 but no associated projectFound a module with path ..\..\..\SharedModules\SharedModule_LockProcess\Source_Code\LockProc_SharedModule but no associated projectFound a module with path ..\..\..\SharedModules\BW_SDI_Client\BW_Shared_SDI_v1 but no associated projectFound a module with path ..\BW_Resolve_MasterCrewData_v1.module but no associated projectFound a module with path ..\BW_Resolve_MasterCrewData_v1 but no associated projectDiscovered a new module com.tui.bw:BW_Resolve_MasterCrewData_v1.parent BW_Resolve_MasterCrewData_v1.parent
Modules changed, recalculating dependency graph
[BW_Resolve_MasterCrewData_v1.parent] $ /opt/java/jdk1.7.0_71//bin/java -cp /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-agent-1.5.jar:/home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/boot/plexus-classworlds-2.5.1.jar:/home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/conf/logging jenkins.maven3.agent.Maven31Main /home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven /home/tibco/.jenkins/war/WEB-INF/lib/remoting-2.47.jar /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven31-interceptor-1.5.jar /home/tibco/.jenkins/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-commons-1.5.jar 39438
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f /home/tibco/.jenkins/jobs/IF34/xyz/BW_Resolve_MasterCrewData_v1.parent/pom.xml install
[INFO] Scanning for projects...
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]   
[ERROR]   The project com.tibco.bw:BW_Shared_CLE_v1:0.5.0-SNAPSHOT (/home/tibco/.jenkins/jobs/IF34/xyz/BW_Shared_CLE_v1/pom.xml) has 1 error
[ERROR]     Unknown packaging: bwmodule @ line 14, column 14
[ERROR]   
[ERROR]   The project com.tibco.bw:LockProc_SharedModule:0.5.0-SNAPSHOT (/home/tibco/.jenkins/jobs/IF34/xyz/LockProc_SharedModule/pom.xml) has 1 error
[ERROR]     Unknown packaging: bwmodule @ line 14, column 14
[ERROR]   
[ERROR]   The project com.tibco.bw:BW_Shared_SDI_v1:0.5.0-SNAPSHOT (/home/tibco/.jenkins/jobs/IF34/xyz/BW_Shared_SDI_v1/pom.xml) has 1 error
[ERROR]     Unknown packaging: bwmodule @ line 14, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
channel stopped
[workspace] $ /home/tibco/.jenkins/tools/hudson.tasks.Maven_MavenInstallation/DEV_Maven/bin/mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.100 s
[INFO] Finished at: 2016-11-18T09:52:47+01:00
[INFO] Final Memory: 12M/481M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy, pre-clean, clean, post-clean. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE`

**Comment by John-Zg** [comment]
I think the problem from above is solved. rahulkamdars comment was the solution. Also, the reason for the second problem was that maven on the server could not resolve the tibco maven plugin. Copying into the repository solved it. 
Now, we have a different problem. But I will create a new issue for that. This can be closed. Thanks a lot.

**Comment by Monisha-tibco** [comment]
Error TIBCO-THOR-FRWK-CMN-500102: Ear file [file:/tmp/upload.tea2264254108345290451/bw.mc-O-SN-USERS.application-1.0.17.jar] is not valid, reason Manifest is not present
