### ISSUE TITLE
500 Error executing the Unit Testing on BW 6.6.1 with 2.7.1

### ISSUE THREAD

**Issue by alexandrev** [TIBCOSoftware/bw6-plugin-maven#507]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->
Maven Plugin version: 2.7.1

Maven version: 3.6.3

Product :  TIBCO ActiveMatrix Businessworks 6

Product version: 6.6.1

Component: Unit Testing

**Steps to reproduce the issue:**
1. Executing Maven plugin on BW 6.6.1 to run a Unit Testing on a simple application
2.
3.

**Additional environment details if any:**

**Describe the results you received:** I'm getting the following error:

[INFO] Starting Tests in Module : consumer.module
[INFO] Uploading tests for Processes in Module :  consumer.module
 consumer.module.SubProcess
javax.ws.rs.InternalServerErrorException: HTTP 500 Server Error
        at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
        at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
        at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTestsPerModule(BWTestRunner.java:138)
        at com.tibco.bw.maven.plugin.test.rest.BWTestRunner.runTests(BWTestRunner.java:106)
        at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.runTests(BWTestExecutor.java:177)
        at com.tibco.bw.maven.plugin.test.setuplocal.BWTestExecutor.execute(BWTestExecutor.java:47)
        at com.tibco.bw.maven.plugin.test.BWTestMojo.execute(BWTestMojo.java:75)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Describe the results you expected:**

Test to be executed.

**Additional information you deem important (e.g. issue happens only occasionally):**

It happes each time I run the process.

**Comment by ahansa** [comment]
Hi @alexandrev ,
Cloud you please try using the updated btw file attached. The one in your project has <lang> tag missing 
`<Lang>urn:oasis:names:tc:wsbpel:2.0:sublang:xslt1.0</Lang>`
Let me know if that works.

[consumer.module1.bwt.zip](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/5346513/consumer.module1.bwt.zip)
cc @vpawar-ai
