### ISSUE TITLE
Mavin Package failing with  Failed to create BW EAR Archive: NullPointerException

### ISSUE THREAD

**Issue by jayasimhagithub** [TIBCOSoftware/bw6-plugin-maven#539]
Hi, 

We are trying to Maven  build for an application in BW 6.6.1 studio, Maven plugin (2.7.1) with
 mvn package . 

It is failing while building  plugin com.tibco.custom.jms.provider and adding  it to application Module..
As we don't see any clue with the below error logs , If anybody came  across  the same issue please share your resolution steps if any .

Build Logs:

[INFO] --- bw6-maven-plugin:2.7.1:bwear (default-bwear) @ YardBroker.application ---
[DEBUG] Configuring mojo com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear from plugin realm ClassRealm[extension>com.tibco.plugins:bw6-maven-plugin:2.7.1, parent: sun.misc.Launcher$AppClassLoader@18b4aac2]
[DEBUG] Configuring mojo 'com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear' with basic configurator -->
[DEBUG]   (f) outputDirectory = C:\ProjectAccount\Project\YARD\Yard_Maven_project\YardBroker.application\target
[DEBUG]   (f) project = MavenProject: com.tibco.bw:YardBroker.application:1.0.0-SNAPSHOT @ C:\ProjectAccount\Project\YARD\Yard_Maven_project\YardBroker.application\pom.xml
[DEBUG]   (f) projectBasedir = C:\ProjectAccount\Project\YARD\Yard_Maven_project\YardBroker.application
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@4afbb6c2
[DEBUG] -- end configuration --
[INFO] BWEARPackager Mojo started ...
[INFO] Updated the Manifest version 
[INFO] The OSGi verion is 1.0.0.202012151702 for Maven version of 1.0.0.202012151702
[INFO] Adding Modules to the EAR file
[DEBUG] Adding Modules to the Application EAR
[INFO] Adding Module JAR with name YardBroker_1.0.0.202012151702.jar with version 1.0.0.202012151702
[INFO] Adding Module JAR with name com.tibco.custom.jms.provider_1.0.0.202012151702.jar with version 1.0.0.202012151702
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\com\tibco\plugins\com.tibco.bw.palette.shared\6.1.100\com.tibco.bw.palette.shared-6.1.100.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\css-4.0.0\0.0.0\css-4.0.0-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\frameworkutilities-4.0.0\0.0.0\frameworkutilities-4.0.0-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\fwmetrics-5.1.0\0.0.0\fwmetrics-5.1.0-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\log4j-1.2.15\0.0.0\log4j-1.2.15-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\log4j-api-2.2\0.0.0\log4j-api-2.2-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\log4j-core-2.2\0.0.0\log4j-core-2.2-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\ojdbc6\0.0.0\ojdbc6-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\spring-web-1.2.3\0.0.0\spring-web-1.2.3-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\TIBCrypt\0.0.0\TIBCrypt-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\tempbw\tibjms\0.0.0\tibjms-0.0.0.jar
[DEBUG] Dependency file is C:\Users\3851336\.m2\repository\com\tibco\bw\com.tibco.bw.sharedresource.jms.runtime\1.0.0\com.tibco.bw.sharedresource.jms.runtime-1.0.0.jar
[ERROR] Failed to add modules to the Application
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YardBroker.application.parent ...................... SUCCESS [  0.006 s]
[INFO] com.tibco.custom.jms.provider ...................... SUCCESS [  4.050 s]
[INFO] YardBroker ......................................... SUCCESS [  2.120 s]
[INFO] YardBroker.application ............................. FAILURE [  0.548 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:43 min
[INFO] Finished at: 2020-12-15T17:02:09-05:00
[INFO] Final Memory: 15M/90M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear (default-bwear) on project YardBroker.application: Failed to create BW EAR Archive: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear (default-bwear) on project YardBroker.application: Failed to create BW EAR Archive 
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create BW EAR Archive 
	at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute(BWEARPackagerMojo.java:117)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.tibco.bw.maven.plugin.utils.BWProjectUtils.getModuleVersion(BWProjectUtils.java:30)
	at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.addModules(BWEARPackagerMojo.java:231)
	at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute(BWEARPackagerMojo.java:110)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :YardBroker.application
Picked up _JAVA_OPTIONS: -Xmx512M

**Comment by vpawar-ai** [comment]
Please share the application code to reproduce the issue. You can share it via TIBCO support case and share the case number here if the artifacts can't be shared on github.

**Comment by jayasimhagithub** [comment]
Thank you. The issue got resolved  after we removed the  duplicate dependencies  which was added in the customplugin project pom.xml

**Comment by jayasimhagithub** [comment]
Hi Pawar

The above issue Nullpointer Exception has occurred in BW studio and  After I remove the dependencies and rebuild  the project , I am able to create the ear using mvn package.

But I am facing the same issue in Linux.  
I have specified the pom.xml  below  which are using in my project  , Could you please advise if I am missing anything in  our pom.xml ,  


Customplugin pom.xml:
--------------------------
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tibco.bw</groupId>
    <artifactId>YardBroker.application.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../YardBroker.application.parent</relativePath>
  </parent>
  <artifactId>com.tibco.custom.jms.provider</artifactId>
  <packaging>bwmodule</packaging>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <outputDirectory>target/classes</outputDirectory>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.7.1</version>
        <extensions>true</extensions>
      </plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>
    </plugins>
  </build>
<dependencies>
<dependency>
<groupId>com.tibco.bw</groupId>
<artifactId>com.tibco.bw.sharedresource.jms.runtime</artifactId>
<version>1.0.0</version>
<scope>provided</scope>
</dependency>
<dependency>
<groupId>org.eclipse.osgi</groupId>
<artifactId>org.eclipse.osgi</artifactId>
<version>1.0.0</version>
<scope>provided</scope>
</dependency>
<dependency>
<groupId>com.tibco.bw</groupId>
<artifactId>jvax.jms2.0</artifactId>
<version>1.0.0</version>
<scope>provided</scope>
</dependency>
</dependencies>
</project>

Application Pom.xml:
-----------------
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.tibco.bw</groupId>
    <artifactId>YardBroker.application.parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../YardBroker.application.parent</relativePath>
  </parent>
  <artifactId>YardBroker.application</artifactId>
  <packaging>bwear</packaging>
  <properties>
    <skipTests>false</skipTests>
    <bw.Home>/bw/6.6</bw.Home>
    <project.type>None</project.type>
    <failIfNoTests>false</failIfNoTests>
    <tibco.Home>/opt/tibco</tibco.Home>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.7.1</version>
        <extensions>true</extensions>
      </plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>
    </plugins>
  </build>
  <reporting>
    <plugins>
      <plugin>
        <groupId>com.tibco.plugins</groupId>
        <artifactId>bw6-maven-plugin</artifactId>
        <version>2.7.1</version>
      </plugin>
    </plugins>
  </reporting>
  <dependencies>
  	<dependency>
  		<groupId>com.tibco.bw</groupId>
  		<artifactId>com.tibco.custom.jms.provider</artifactId>
  		<version>1.0.0</version>
  	</dependency>
  </dependencies>
</project>

Parent pom.xml:
------------
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.tibco.bw</groupId>
  <artifactId>YardBroker.application.parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>../com.tibco.custom.jms.provider</module>
    <module>../YardBroker</module>
    <module>../YardBroker.application</module>
  </modules>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.7.1</version>
      </plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.8.1</version>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
</plugin>

    </plugins>
  </build>
</project>



Erro Log:
---------

[INFO] --- bw6-maven-plugin:2.7.1:bwear (default-bwear) @ YardBroker.application ---
[DEBUG] Configuring mojo com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear from plugin realm ClassRealm[extension>com.tibco.plugins:bw6-maven-plugin:2.7.1, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo 'com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear' with basic configurator -->
[DEBUG]   (f) outputDirectory = /opt/sample/tibco/Yard_Maven_Project_Dec12/YardBroker.application/target
[DEBUG]   (f) project = MavenProject: com.tibco.bw:YardBroker.application:1.0.0-SNAPSHOT @ /opt/sample/tibco/Yard_Maven_Project_Dec12/YardBroker.application/pom.xml
[DEBUG]   (f) projectBasedir = /opt/sample/tibco/Yard_Maven_Project_Dec12/YardBroker.application
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@3ed03652
[DEBUG] -- end configuration --
[INFO] BWEARPackager Mojo started ...
[INFO] Updated the Manifest version
[INFO] The OSGi verion is 1.0.0.202012181615 for Maven version of 1.0.0.202012181615
[INFO] Adding Modules to the EAR file
[DEBUG] Adding Modules to the Application EAR
[INFO] Adding Module JAR with name YardBroker_1.0.0.202012181615.jar with version 1.0.0.202012181615
[INFO] Adding Module JAR with name com.tibco.custom.jms.provider-1.0.0.jar with version 1.0.0
[DEBUG] Dependency file is /home/tibco/.m2/repository/com/tibco/plugins/com.tibco.bw.palette.shared/6.1.100/com.tibco.bw.palette.shared-6.1.100.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/tibjms/0.0.0/tibjms-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/TIBCrypt/0.0.0/TIBCrypt-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/spring-web-1.2.3/0.0.0/spring-web-1.2.3-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/ojdbc6/0.0.0/ojdbc6-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/log4j-core-2.2/0.0.0/log4j-core-2.2-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/log4j-api-2.2/0.0.0/log4j-api-2.2-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/log4j-1.2.15/0.0.0/log4j-1.2.15-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/fwmetrics-5.1.0/0.0.0/fwmetrics-5.1.0-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/frameworkutilities-4.0.0/0.0.0/frameworkutilities-4.0.0-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/tempbw/css-4.0.0/0.0.0/css-4.0.0-0.0.0.jar
[DEBUG] Dependency file is /home/tibco/.m2/repository/com/tibco/bw/com.tibco.bw.sharedresource.jms.runtime/1.0.0/com.tibco.bw.sharedresource.jms.runtime-1.0.0.jar
[ERROR] Failed to add modules to the Application
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for YardBroker.application.parent 1.0.0-SNAPSHOT:
[INFO]
[INFO] YardBroker.application.parent ...................... SUCCESS [  0.134 s]
[INFO] com.tibco.custom.jms.provider ...................... SUCCESS [  2.962 s]
[INFO] YardBroker ......................................... SUCCESS [  1.602 s]
[INFO] YardBroker.application ............................. FAILURE [  0.354 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:18 min
[INFO] Finished at: 2020-12-18T16:15:58Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear (default-bwear) on project YardBroker.application: Failed to create BW EAR Archive : NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.tibco.plugins:bw6-maven-plugin:2.7.1:bwear (default-bwear) on project YardBroker.application: Failed to create BW EAR Archive
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create BW EAR Archive
    at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute (BWEARPackagerMojo.java:117)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at com.tibco.bw.maven.plugin.utils.BWProjectUtils.getModuleVersion (BWProjectUtils.java:30)
    at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.addModules (BWEARPackagerMojo.java:231)
    at com.tibco.bw.maven.plugin.application.BWEARPackagerMojo.execute (BWEARPackagerMojo.java:110)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :YardBroker.application
-bash-4.2$
