### ISSUE TITLE
TIBCO-THOR-FRWK-CMN-500000: java.lang.IllegalArgumentException: invalid version "null": non-numeric "null"

### ISSUE THREAD

**Issue by rahulkamdar** [TIBCOSoftware/bw6-plugin-maven#54]
Hi,
We try to deploy the application IF34 with maven plugin and Jenkins.
 
Unfortunately, we get the below error : 
[INFO] --- bw6-maven-plugin:1.1.0:bwinstall (default-bwinstall) @ BW_Resolve_MasterCrewData_v1 ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[INFO] Connected to BWAgent. Agents found
[INFO] Agent Name -> {agent-name-here}
[INFO] Domain exists with Name -> {domain-name}
[INFO] AppSpace exists with Name -> {app-space-name} in Domain -> oneAviation_Jetair_TEST
[INFO] AppNode exists with Name -> Node001 in Domain -> {app-node-name} and in AppSpace -> {app-space-name}
[INFO] AppNode HTTP Port  -> 8075. AppNode OSGi Port -> -1
[INFO] AppSpace is Running.
[INFO] Uploading the Archive file -> BW_Resolve_MasterCrewData_v1_1.12.0.ear
[ERROR]
com.tibco.bw.maven.plugin.admin.client.ClientException: TIBCO-THOR-FRWK-CMN-500000: java.lang.IllegalArgumentException: invalid version "null": non-numeric "null" (400)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:530)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:301)
        at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:171)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at hudson.maven.Maven3Builder.call(Maven3Builder.java:134)
        at hudson.maven.Maven3Builder.call(Maven3Builder.java:69)
        at hudson.remoting.UserRequest.perform(UserRequest.java:121)
        at hudson.remoting.UserRequest.perform(UserRequest.java:49)
        at hudson.remoting.Request$2.run(Request.java:324)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
 
 
So, the package cannot be uploaded. Please find the application with the POM files attached. The maven goal we use is “install”.
This seems like a known issue:
https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/28
 
Please give advice how to proceed.

**Comment by John-Zg** [comment]
Hi Rahul, 

this issue seems to be resolved here: https://github.com/TIBCOSoftware/bw6-plugin-maven/issues/50 and can be closed.

**Comment by rahulkamdar** [comment]
Thanks @John-Zg - checking with the user who originally reported this.

**Comment by rahulkamdar** [comment]
Closing this per feedback received.
