### ISSUE TITLE
POM Generation UI does not open

### ISSUE THREAD

**Issue by srishtihasijani** [TIBCOSoftware/bw6-plugin-maven#567]
Maven Plugin version:

Maven version:

Product : Either of TIBCO ActiveMatrix Businessworks 6 OR TIBCO Businessworks Container edition

Product version:

Component: Either of Maven Eclipse Plugin or Maven build plugin

**Steps to reproduce the issue:**
1.
2.
3.

**Additional environment details if any:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by srishtihasijani** [comment]
!SESSION 2021-02-20 12:25:22.808 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_221
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -showlocation
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -showlocation

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2021-02-20 12:25:46.903
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.bw.sharedresource.jdbc.driver.template 4 0 2021-02-20 12:25:46.907
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jdbc.driver.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.bw.sharedresource.jms.provider.template 4 0 2021-02-20 12:25:46.922
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jms.provider.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.bw.sharedresource.jms.provider.template 4 0 2021-02-20 12:25:46.923
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.bw.sharedresource.jms.provider.template. The component header value is OSGI-INF/*.xml

!ENTRY com.tibco.zion.dc 4 0 2021-02-20 12:25:46.952
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.zion.dc. The component header value is OSGI-INF/com.tibco.zion.dc.service.impl.ProfileEncryptionServiceImpl.xml

!ENTRY com.tibco.zion.dc 4 0 2021-02-20 12:25:46.952
!MESSAGE [SCR] Component definition XMLs not found in bundle com.tibco.zion.dc. The component header value is OSGI-INF/com.tibco.zion.dc.service.impl.ProfileEncryptionServiceImpl.xml

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.200
!MESSAGE Both 'com.tibco.amf.sharedresource.model.transport.eclipse' and 'com.tibco.amf.sharedresource.model.transport.eclipse' register a package for 'http://xsd.tns.tibco.com/amf/models/sharedresource/httpconnector'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.203
!MESSAGE Both 'com.tibco.bw.core.model.eclipse' and 'com.tibco.bw.core.model.eclipse' register a package for 'http://ns.tibco.com/bw/core/internalactivity'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.204
!MESSAGE Both 'com.tibco.bw.it.model' and 'com.tibco.bw.it.model' register a package for 'http://xsd.tns.tibco.com/amf/models/sca/implementationtype/BW'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.206
!MESSAGE Both 'com.tibco.bw.sharedresource.http.model' and 'com.tibco.bw.sharedresource.http.model' register a package for 'http://xsd.tns.tibco.com/bw/models/sharedresource/httpclient'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.207
!MESSAGE Both 'com.tibco.amf.sharedresource.model.data.eclipse' and 'com.tibco.bw.sharedresource.jdbc.model' register a package for 'http://xsd.tns.tibco.com/amf/models/sharedresource/jdbc'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.209
!MESSAGE Both 'com.tibco.amf.sca.model.eclipse' and 'com.tibco.bw.sharedresource.ws.policy.model' register a package for 'http://schemas.xmlsoap.org/ws/2004/09/policy'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.209
!MESSAGE Both 'com.tibco.amf.wsdl.extensions.eclipse' and 'com.tibco.bw.wsdl.extensions' register a package for 'http://xsd.tns.tibco.com/wsdl/models/extensions/soap/tibcojms'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.210
!MESSAGE Both 'com.tibco.amf.wsdl.extensions.eclipse' and 'com.tibco.bw.wsdl.extensions' register a package for 'http://xsd.tns.tibco.com/wsdl/models/soap12'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.216
!MESSAGE Both 'com.tibco.bw.sharedresource.identity.model' and 'com.tibco.bw.sharedresource.ws.policy.model' register an extension parser for 'policy'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.216
!MESSAGE Both 'com.tibco.bw.sharedresource.trinity.securityprovider.model' and 'com.tibco.trinity.securityprovider.model.eclipse' register an extension parser for 'auth'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.217
!MESSAGE Both 'com.tibco.bw.sharedresource.trinity.securityprovider.model' and 'com.tibco.trinity.securityprovider.model.eclipse' register an extension parser for 'identity'

!ENTRY org.eclipse.emf.ecore 2 0 2021-02-20 12:26:05.218
!MESSAGE Both 'com.tibco.bw.sharedresource.trinity.securityprovider.model' and 'com.tibco.trinity.securityprovider.model.eclipse' register an extension parser for 'userid'

!ENTRY org.eclipse.ui 2 0 2021-02-20 12:26:05.671
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:05.671
!MESSAGE Commands should really have a category: plug-in='com.tibco.amf.tools.migration2x.ui', id='com.tibco.amf.tools.migration2x.ui.migrateTo3xCommand', categoryId='com.tibco.amf.tools.composite.resources.ui.TasksCategory'
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:05.671
!MESSAGE Commands should really have a category: plug-in='com.tibco.amf.tools.packager.ui', id='com.tibco.amf.tools.packager.ui.createDaa.command', categoryId='tibco.category.soa_platform'
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:05.671
!MESSAGE Commands should really have a category: plug-in='com.tibco.bw.binding.soap.axis2.design', id='com.tibco.bw.binding.soap.axis2.design.generateWSDL', categoryId='tibco.category.soa_platform'

!ENTRY org.eclipse.ui 2 0 2021-02-20 12:26:06.345
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:06.345
!MESSAGE Commands should really have a category: plug-in='com.tibco.amf.tools.migration2x.ui', id='com.tibco.amf.tools.migration2x.ui.migrateTo3xCommand', categoryId='com.tibco.amf.tools.composite.resources.ui.TasksCategory'
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:06.345
!MESSAGE Commands should really have a category: plug-in='com.tibco.amf.tools.packager.ui', id='com.tibco.amf.tools.packager.ui.createDaa.command', categoryId='tibco.category.soa_platform'
!SUBENTRY 1 org.eclipse.ui 2 0 2021-02-20 12:26:06.345
!MESSAGE Commands should really have a category: plug-in='com.tibco.bw.binding.soap.axis2.design', id='com.tibco.bw.binding.soap.axis2.design.generateWSDL', categoryId='tibco.category.soa_platform'

!ENTRY org.eclipse.egit.ui 2 0 2021-02-20 12:26:22.636
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\shasijan'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:22.994
!MESSAGE Constraint "com.tibco.amf.design.sr.core.internal.validation.constraints.SharedResourceNotInWorkspace" could not find target EMF type "Property."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.046
!MESSAGE Constraint "com.tibco.bw.sharedresource.http.design.com.tibco.amf.design.sr.transport.http.ssl.namedResourceReferenceValueNotEmpty" could not find target EMF type "NamedResourceReference."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.093
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.identity.subject.editor.com.tibco.trinity.identity.subject.editor.validation.HasOneStoreConstraint" could not find target EMF type "SubjectConfiguration."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.096
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.identity.subject.editor.com.tibco.trinity.identity.subject.editor.validation.KeyAliasNotNullConstraint" could not find target EMF type "SubjectConfiguration."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.097
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.identity.subject.editor.com.tibco.trinity.identity.subject.editor.validation.KeyPasswordNotNullConstraint" could not find target EMF type "SubjectConfiguration."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.098
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.identity.trust.editor.constraint" could not find target EMF type "TrustConfiguration."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.108
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.ssl.editor.com.tibco.trinity.ssl.editor.invalid.remote.host.constraint" could not find target EMF type "SSLServerConfiguration."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.110
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.ssl.editor.com.tibco.bw.sharedresource.trinity.ssl.client.editor.trust.namedResourceReferenceValueNotEmpty" could not find target EMF type "NamedResourceReference."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.111
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.ssl.editor.com.tibco.bw.sharedresource.trinity.ssl.client.editor.subject.namedResourceReferenceValueNotEmpty" could not find target EMF type "NamedResourceReference."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.120
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.ssl.editor.com.tibco.bw.sharedresource.trinity.ssl.server.editor.trust.namedResourceReferenceValueNotEmpty" could not find target EMF type "NamedResourceReference."

!ENTRY org.eclipse.emf.validation 2 70 2021-02-20 12:26:23.120
!MESSAGE Constraint "com.tibco.bw.sharedresource.trinity.ssl.editor.com.tibco.bw.sharedresource.trinity.ssl.server.editor.subject.namedResourceReferenceValueNotEmpty" could not find target EMF type "NamedResourceReference."

!ENTRY com.tibco.xpd.fragments 4 0 2021-02-20 12:26:23.342
!MESSAGE com.tibco.xpd.fragments.internal.FragmentsManager$5.run(FragmentsManager.java:787) FragmentsManager.initialize(): No root categories found!!!

!ENTRY com.tibco.bw.core.design.process.editor 1 0 2021-02-20 12:26:23.616
!MESSAGE ".com.tibco.bw.rad/BWApplication.launch" file is synchronized.

!ENTRY com.tibco.bw.core.design.process.editor 1 0 2021-02-20 12:26:23.651
!MESSAGE ".com.tibco.bw.rad/runtime.target" file is synchronized.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:48.490
!MESSAGE class com.tibco.zion.dc.util.DeploymentConfigurationsHelper - (savePackageUnit) : Encryption settings are empty.Saving normally.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.517
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.517
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.517
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.582
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:48.589
!MESSAGE class com.tibco.zion.dc.util.DeploymentConfigurationsHelper - (savePackageUnit) : Encryption settings are empty.Saving normally.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.655
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:48.659
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.090
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.126
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.134
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.143
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.148
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.153
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.157
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.158
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.166
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.173
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.185
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.217
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.223
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.236
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:56.238
!MESSAGE class com.tibco.zion.dc.util.DeploymentConfigurationsHelper - (savePackageUnit) : Encryption settings are empty.Saving normally.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:56.273
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY org.eclipse.bpel.validator 1 0 2021-02-20 12:26:58.043
!MESSAGE Validator Startup 95ms

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.568
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.572
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.574
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.577
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.580
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.583
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.586
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.589
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.592
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.593
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.598
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.601
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.604
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.dc 1 0 2021-02-20 12:26:58.607
!MESSAGE Encryption setings are not available for project - gf.application

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.614
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:26:58.624
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:08.389
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.558
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.568
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.570
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.576
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.576
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.576
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.584
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.586
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:27:10.589
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY org.eclipse.ui 4 0 2021-02-20 12:27:11.060
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject
	at com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:32)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:74)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.ClassNotFoundException: com.tibco.zion.project.core.ContainerPreferenceProject cannot be found by bw6.studio.maven.plugin_1.2.2.201706121001
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more

!ENTRY org.eclipse.ui 4 0 2021-02-20 12:33:37.908
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject
	at com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:32)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:74)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.175
!MESSAGE BWDesigntimeResourceValidationHelper.validateActivityRequiredPlugin() Process [gf.Process], Activity [Timer]

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.176
!MESSAGE   bwActivity = com.tibco.bw.core.model.bwext.impl.BWActivityImpl@66e58375 (activityTypeID: bw.generalactivities.timer, version: 6.0.0.001)

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.177
!MESSAGE   activityTypeId=null, isMissingRequiredPlugin=false, exception=null

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.189
!MESSAGE BWDesigntimeResourceValidationHelper.validateActivityRequiredPlugin() Process [gf.Process], Activity [CreateFile]

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.190
!MESSAGE   bwActivity = com.tibco.bw.core.model.bwext.impl.BWActivityImpl@6a895465 (activityTypeID: bw.file.create, version: null)

!ENTRY com.tibco.bw.core.design.resource 1 0 2021-02-20 12:39:07.190
!MESSAGE   activityTypeId=null, isMissingRequiredPlugin=false, exception=null

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:39:07.248
!MESSAGE Loading default.substvar as a plaintext file.

!ENTRY org.eclipse.ui 4 0 2021-02-20 12:39:12.862
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoClassDefFoundError: com/tibco/zion/project/core/ContainerPreferenceProject
	at com.tibco.bw.studio.maven.wizard.MavenWizard.addPages(MavenWizard.java:32)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:619)
	at org.eclipse.jface.window.Window.create(Window.java:435)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1101)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.tibco.bw.studio.maven.action.MavenPOMProcessor.run(MavenPOMProcessor.java:74)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:253)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY com.tibco.zion.common 1 0 2021-02-20 12:40:46.032
!MESSAGE Loading default.substvar as a plaintext file.

**Comment by SujataDarekar** [comment]
@srishtihasijani  Can you please check if Maven Plugin is installed properly or not? You can check in Help -> Installation Details.
In Installation Detail go to "Installed Software" tab and type "Maven". You should able to see "Tibco BusinessWorks Studio feature for Maven " with installed maven version.  Also let us know what is the Deployment Target set for the Project.

**Comment by ukuppa-tibco** [comment]
Please check all the pre-requisites if you have installed Apache Maven along with Maven plugin without any issues/errors.
Closing this issue for now.
