### ISSUE TITLE
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null

### ISSUE THREAD

**Issue by Tantino** [TIBCOSoftware/bw6-plugin-maven#65]
Maven Plugin version: 1.2.0

Maven version:
 mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Program Files\apache-maven-3.3.3
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_77\jre
Default locale: es_ES, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

Product : TIBCO ActiveMatrix Businessworks 6.3.5

Product version:

Component: Maven build plugin

**Steps to reproduce the issue:**
1. mvn install

**Describe the results you received:**

[ERROR]
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:353)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:238)
        at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:169)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:519)
        at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:347)
        ... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] CORE.solution.parent ............................... SUCCESS [  0.349 s]
[INFO] CORE.arq ........................................... SUCCESS [  2.839 s]
[INFO] CORE.bbdd .......................................... SUCCESS [  0.340 s]
[INFO] CORE.app ........................................... SUCCESS [  1.445 s]
[INFO] CORE.solution ...................................... SUCCESS [  8.687 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.859 s
[INFO] Finished at: 2017-03-02T17:05:54+01:00
[INFO] Final Memory: 25M/198M
[INFO] ------------------------------------------------------------------------

**Describe the results you expected:**

EAR file not upload

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fcenedes** [comment]
BW Version : 6.3.5
TEA 2.2.0-H8

i have updated the RemoteDeployer.java class, and updated the mvn plugnin accordlingly. i Still have the same problem : 

[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] app1.parent
[INFO] app1.module
[INFO] app1
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building app1.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ app1.parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ app1.parent ---
[INFO] Installing /Users/fcenedes/bitbucket/corelogic_app_1/app1.parent/pom.xml to /Users/fcenedes/.m2/repository/com/tibco/bw/app1.parent/1.0.0-SNAPSHOT/app1.parent-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building app1.module 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ app1.module ---
[INFO] Deleting /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ app1.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ app1.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ app1.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ app1.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ app1.module ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ app1.module ---
[INFO] Module Packager Mojo started for Module app1.module ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target/app1.module_1.0.0.201703021741.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target/app1.module_1.0.0.201703021741.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ app1.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ app1.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ app1.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ app1.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ app1.module ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwmodule (default-bwmodule) @ app1.module ---
[INFO] Module Packager Mojo started for Module app1.module ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target/app1.module_1.0.0.201703021741.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target/app1.module_1.0.0.201703021741.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ app1.module ---
[INFO] Installing /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/target/app1.module_1.0.0.201703021741.jar to /Users/fcenedes/.m2/repository/com/tibco/bw/app1.module/1.0.0-SNAPSHOT/app1.module-1.0.0-SNAPSHOT.jar
[INFO] Installing /Users/fcenedes/bitbucket/corelogic_app_1/app1.module/pom.xml to /Users/fcenedes/.m2/repository/com/tibco/bw/app1.module/1.0.0-SNAPSHOT/app1.module-1.0.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building app1 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ app1 ---
[INFO] Deleting /Users/fcenedes/bitbucket/corelogic_app_1/app1/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ app1 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ app1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ app1 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ app1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ app1 ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ app1 ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: /Users/fcenedes/bitbucket/corelogic_app_1/app1/target/app1_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ app1 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ app1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ app1 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/fcenedes/bitbucket/corelogic_app_1/app1/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ app1 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ app1 ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwear (default-bwear) @ app1 ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: /Users/fcenedes/bitbucket/corelogic_app_1/app1/target/app1_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ app1 ---
[INFO] Installing /Users/fcenedes/bitbucket/corelogic_app_1/app1/target/app1_1.0.0.ear to /Users/fcenedes/.m2/repository/com/tibco/bw/app1/1.0.0-SNAPSHOT/app1-1.0.0-SNAPSHOT.ear
[INFO] Installing /Users/fcenedes/bitbucket/corelogic_app_1/app1/pom.xml to /Users/fcenedes/.m2/repository/com/tibco/bw/app1/1.0.0-SNAPSHOT/app1-1.0.0-SNAPSHOT.pom
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.0:bwinstall (default-bwinstall) @ app1 ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[INFO] Connected to BWAgent. Agents found.
[INFO] Agent Name -> ec2-54-194-75-176.eu-west-1.compute.amazonaws.com
[INFO] Domain exists with Name -> devdomain
[INFO] AppSpace exists with Name -> devspace in Domain -> devdomain
[INFO] AppNode exists with Name -> app1Node in Domain -> devdomain and in AppSpace -> devspace
[INFO] AppNode HTTP Port  -> 8064. AppNode OSGi Port -> 8065
[INFO] Starting AppSpace with name -> devspace in Domain -> devdomain
[INFO] domain -> devdomain earName -> app1_1.0.0.ear Ear file to be uploaded -> /Users/fcenedes/bitbucket/corelogic_app_1/app1/target/app1_1.0.0.ear
[INFO] Application exists with name -> app1. Undeploying the Application as Redeploy flag is true.
[INFO] Uploading the Archive file -> app1_1.0.0.ear
[INFO] uploadArchiveMethod : JerseyWebTarget { http://54.194.75.176:8079/bw/v1/domains/devdomain/archives?replace=true }
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:359)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:239)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:170)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:522)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:353)
	... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] app1.parent ........................................ SUCCESS [  0.118 s]
[INFO] app1.module ........................................ SUCCESS [  0.614 s]
[INFO] app1 ............................................... SUCCESS [ 12.635 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.327 s
[INFO] Finished at: 2017-03-02T17:41:12+01:00
[INFO] Final Memory: 25M/320M
[INFO] ------------------------------------------------------------------------

**Comment by Tantino** [comment]
the problem is the EAR file is not generate right. This file only have META-INF folder.

Please in my case I execute `mvn clean` and this issue is solved.

**Comment by fcenedes** [comment]
The EAR file is generated correctly, has after this upload failed thru maven, i can upload the SAME EAR file via TEA...

Upload also work with bwadmin

i always issue mvn clean install


MVN Version : 

> Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
> Maven home: /usr/local/Cellar/maven/3.3.9/libexec
> Java version: 1.8.0_25, vendor: Oracle Corporation
> Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "mac os x", version: "10.11.5", arch: "x86_64", family: "mac"
