### ISSUE TITLE
validating a project is resulting in same errors

### ISSUE THREAD

**Issue by luispduarte-novobanco** [TIBCOSoftware/bw6-plugin-maven#654]
Maven Plugin version: 2.8.0

Maven version: 3.8.4

Product : TIBCO ActiveMatrix Businessworks 6

Product version: 6.7.4

Component: Maven build plugin

**Steps to reproduce the issue:**
1.Running the goal validate in a linux machine : mvn -X --s settings.xml com.tibco.plugins:bw6-maven-plugin:2.8.0:bwdesignUtility -DcommandName=validate
2.
3.

**Additional environment details if any:**
linux 6.7

**Describe the results you received:**
[.log](https://github.com/TIBCOSoftware/bw6-plugin-maven/files/8207056/default.log)

Caused by: org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(SWT.java:4467)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:934)
	at org.eclipse.swt.widgets.Display.create(Display.java:918)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:157)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:514)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:505)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1724)
	at org.eclipse.swt.widgets.Display$1.run(Display.java:471)
	at org.eclipse.swt.graphics.Device.getDevice(Device.java:113)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:49)
	at org.eclipse.swt.graphics.Color.<init>(Color.java:78)
	at com.tibco.zion.common.ZionCommon.<clinit>(ZionCommon.java:123)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.loadBundleActivator(BundleContextImpl.java:755)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:706)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	... 121 more

fulle error in attachement

**Describe the results you expected:**
expecting a valid validation project

**Additional information you deem important (e.g. issue happens only occasionally):**

When we run the goal in a windows machine we dont have these error

**Comment by sarundes-tibco** [comment]
@luispduarte-novobanco can you please share complete steps to reproduce the issue

**Comment by sarundes-tibco** [comment]
@ukuppa-tibco  assigning to QA for to reproduce

**Comment by sarundes-tibco** [comment]
JIRA :  https://jira.tibco.com/browse/AMBW-48474
