### ISSUE TITLE
issue | maven 3.5.x is not working

### ISSUE THREAD

**Issue by mshahat** [TIBCOSoftware/bw6-plugin-maven#79]
macos 10.12.4 (16E195)
BWCE 2.2.1 
Maven 3.5.0 
plugin 1.2.1 

running Maven package fails as below. 

rerunning that using maven 3.3.9 is working though 

Thanks 

```
➜ ~/tibco_workspace/projectnamemmmm/logging/Logging_Library mshahat (master) mvn package
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Logging_Library 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ Logging_Library ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/mshahat/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ Logging_Library ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ Logging_Library ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/mshahat/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ Logging_Library ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ Logging_Library ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.1:bwmodule (default-bwmodule) @ Logging_Library ---
[INFO] Module Packager Mojo started for Module Logging_Library ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name /Users/mshahat/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library/target/Logging_Library_1.0.0.201704262010.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: /Users/mshahat/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library/target/Logging_Library_1.0.0.201704262010.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.000 s
[INFO] Finished at: 2017-04-26T20:10:20+01:00
[INFO] Final Memory: 18M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.1:bwmodule (default-bwmodule) on project Logging_Library: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:1.2.1:bwmodule failed.: UnsupportedOperationException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

➜ ~/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library mshahat (master) brew info java
Error: No available formula with the name "java" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.

➜ ~/tibco_workspace/350.beazley-uk/project-01/logging/Logging_Library mshahat (master) brew info jdk
Error: No available formula with the name "jdk" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
```
<!--

If you have a question, please label the issue as question.

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

**Comment by mshahat** [comment]
any input on this one ?

**Comment by fcenedes** [comment]
Hi Mshahat

Can you contact me directly ? so you could test something for me.

regards,
Flo

**Comment by olifly** [comment]
Has there been any progress on this issue?  I'm encountering this as well.

Error produced:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.2:bwmodule (default-bwmodule) on project logger: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:1.2.2:bwmodule failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-bwmodule of goal com.tibco.plugins:bw6-maven-plugin:1.2.2:bwmodule failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableList.set(Collections.java:1311)
	at com.tibco.bw.maven.plugin.module.BWModulePackageMojo.execute(BWModulePackageMojo.java:131)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

**Comment by olifly** [comment]
Just submitted a pull request which should fix this issue: 

https://github.com/TIBCOSoftware/bw6-plugin-maven/pull/95

**Comment by ashutoshbhide** [comment]
Hi @olifly 
You are still using the older version of plugin in your pom file.
Please update it to 1.3.1 in your POM files.

Here is snippet from your logs.
Failed to execute goal com.tibco.plugins:bw6-maven-plugin:1.2.2

Let me know if it works for you.

-Ashutosh
