### ISSUE TITLE
Getting Exception : com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500) with TIB_BW_Maven_Plugin 1.2.1

### ISSUE THREAD

**Issue by rohitbadgaiyan** [TIBCOSoftware/bw6-plugin-maven#82]
Installation configuration BW635+TEA22.
Installed TIB_BW_Maven_Plugin_1.2.1 on the top of BW6.3.5.
Configured project and created POM,
Checked-in + pushed the code to Git repo using Studio,
Jenkins job which has has clean package and installl script failed with below exception:

[INFO] --- bw6-maven-plugin:1.2.1:bwinstall (default-bwinstall) @ a.application ---
[INFO] BWEAR Installer Mojo started ...
[INFO] No Deployment Config File set. Reading the deployment Properties from POM File.
[INFO] Connected to BWAgent. Agents found.
[INFO] Agent Name -> rbadgaiy-t430
[INFO] Domain exists with Name -> Test
[INFO] AppSpace exists with Name -> Test in Domain -> Test
[INFO] AppNode exists with Name -> TestAppnode in Domain -> Test and in AppSpace -> Test
[INFO] AppNode HTTP Port  -> 8062. AppNode OSGi Port -> -1
[INFO] AppSpace is Running.
[INFO] Uploading the Archive file -> a.application_1.0.0.ear
[ERROR] 
com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:353)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.addAndDeployApplication(RemoteDeployer.java:238)
	at com.tibco.bw.maven.plugin.application.BWEARInstallerMojo.execute(BWEARInstallerMojo.java:170)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.tibco.bw.maven.plugin.admin.client.ClientException: null: TIBCO-BW-ADMIN-500000: null (500)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.processErrorResponse(RemoteDeployer.java:519)
	at com.tibco.bw.maven.plugin.admin.client.RemoteDeployer.uploadArchive(RemoteDeployer.java:347)
	... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] a.application.parent ............................... SUCCESS [  0.427 s]
[INFO] a .................................................. SUCCESS [  2.092 s]
[INFO] a.application ...................................... SUCCESS [  4.687 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.065 s
[INFO] Finished at: 2017-05-11T15:58:24+05:30
[INFO] Final Memory: 18M/211M
[INFO] ------------------------------------------------------------------------
Finished: SUCCESS

**Comment by SujataDarekar** [comment]
Hi @rohitbadgaiyan,
     I tried with Maven version 1.3.0 Issue is not occurring at my end. Please try with latest version 1.3.0 of Maven and let me know if you still facing the issue. Marking the issue as closed.
