### ISSUE TITLE
Question - Is it possible to run the mvn clean package initialize docker:build docker:start -Ddocker.property.file=docker-dev.properties command without using TLS?  

### ISSUE THREAD

**Issue by dtredinnick13** [TIBCOSoftware/bw6-plugin-maven#89]
Maven Plugin version:1.2.2

Maven version:3.3.9

Product : TIBCO Businessworks Container edition

Product version:2.3

Component: Maven build plugin

**Steps to reproduce the issue:**
1. execute mvn clean package initialize docker:build docker:start -Ddocker.property.file=docker-dev.properties
2. 
3.

**Additional environment details if any:**
I am unable to run sudo dockerd --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem   -H=0.0.0.0:2376 as it hangs on the step 

INFO[0001] IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
 Therefore, even though I have all the certs created, docker won't recognize them.  I tried deleting the line bwdocker.certPath=/home/dtredinnick/.docker from the file docker-dev.properties to see if that would allow me to connect without having to use TLS, but still get the same results.

**Describe the results you received:**
dtredinnick@devopsft:~/dev/testworkspace/SimpleProject.parent$ mvn -e clean package initialize docker:build docker:start -Ddocker.property.file=docker-dev.properties
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Starting Maven Build for BW6 Project.................................
[INFO] Checking for In-Project JAR dependencies if any and Pushing them to Local Maven Repository
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] SimpleProject.parent
[INFO] SimpleProject.module
[INFO] SimpleProject
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SimpleProject.parent 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SimpleProject.parent ---
[INFO] 
[INFO] --- docker-maven-plugin:0.14.2:build (default-cli) @ SimpleProject.parent ---
[INFO] 
[INFO] --- docker-maven-plugin:0.14.2:start (default-cli) @ SimpleProject.parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SimpleProject.module 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SimpleProject.module ---
[INFO] Deleting /home/dtredinnick/dev/testworkspace/SimpleProject.module/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ SimpleProject.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/dtredinnick/dev/testworkspace/SimpleProject.module/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ SimpleProject.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ SimpleProject.module ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/dtredinnick/dev/testworkspace/SimpleProject.module/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ SimpleProject.module ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ SimpleProject.module ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.1:bwmodule (default-bwmodule) @ SimpleProject.module ---
[INFO] Module Packager Mojo started for Module SimpleProject.module ...
[INFO] Updated the Manifest version 
[INFO] Removing the externals entries if any. 
[INFO] Created Plugin JAR with name /home/dtredinnick/dev/testworkspace/SimpleProject.module/target/SimpleProject.module_1.0.0.201706121823.jar
[INFO] Adding Maven Dependencies to the Plugin JAR file
[INFO] Creating the Plugin JAR file
[INFO] Building jar: /home/dtredinnick/dev/testworkspace/SimpleProject.module/target/SimpleProject.module_1.0.0.201706121823.jar
[INFO] BW Module Packager Mojo finished execution.
[INFO] 
[INFO] --- docker-maven-plugin:0.14.2:build (default-cli) @ SimpleProject.module ---
[INFO] 
[INFO] --- docker-maven-plugin:0.14.2:start (default-cli) @ SimpleProject.module ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SimpleProject 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SimpleProject ---
[INFO] Deleting /home/dtredinnick/dev/testworkspace/SimpleProject/target
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ SimpleProject ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ SimpleProject ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/dtredinnick/dev/testworkspace/SimpleProject/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ SimpleProject ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ SimpleProject ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/dtredinnick/dev/testworkspace/SimpleProject/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ SimpleProject ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ SimpleProject ---
[INFO] No tests to run.
[INFO] 
[INFO] --- bw6-maven-plugin:1.2.1:bwear (default-bwear) @ SimpleProject ---
[INFO] BWEARPackager Mojo started ...
[INFO] Adding Modules to the EAR file
[INFO] Adding EAR Information to the EAR File
[INFO] Building jar: /home/dtredinnick/dev/testworkspace/SimpleProject/target/SimpleProject_1.0.0.ear
[INFO] BWEARPackager Mojo finished execution
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ SimpleProject ---
[INFO] 
[INFO] --- docker-maven-plugin:0.14.2:build (default-cli) @ SimpleProject ---
[ERROR] DOCKER> Unable to check image [tibco/bwce]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SimpleProject.parent ............................... SUCCESS [  0.772 s]
[INFO] SimpleProject.module ............................... SUCCESS [  1.210 s]
[INFO] SimpleProject ...................................... FAILURE [  0.931 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.573 s
[INFO] Finished at: 2017-06-12T18:23:43-05:00
[INFO] Final Memory: 23M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (default-cli) on project SimpleProject: Unable to check image [tibco/bwce]: Connect to 127.0.0.1:2376 [/127.0.0.1] failed: Connection refused (Connection refused) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.14.2:build (default-cli) on project SimpleProject: Unable to check image [tibco/bwce]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to check image [tibco/bwce]
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to check image [tibco/bwce]
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.hasImage(DockerAccessWithHcClient.java:266)
	at io.fabric8.maven.docker.service.QueryService.hasImage(QueryService.java:147)
	at io.fabric8.maven.docker.service.QueryService.pullIfNotPresent(QueryService.java:188)
	at io.fabric8.maven.docker.service.QueryService.imageRequiresAutoPull(QueryService.java:168)
	at io.fabric8.maven.docker.AbstractDockerMojo.checkImageWithAutoPull(AbstractDockerMojo.java:350)
	at io.fabric8.maven.docker.AbstractBuildSupportMojo.autoPullBaseImage(AbstractBuildSupportMojo.java:88)
	at io.fabric8.maven.docker.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:60)
	at io.fabric8.maven.docker.BuildMojo.buildAndTag(BuildMojo.java:46)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:38)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:164)
	... 22 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:2376 [/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.get(ApacheHttpClientDelegate.java:55)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.hasImage(DockerAccessWithHcClient.java:264)
	... 31 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:244)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	... 44 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ConnectException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :SimpleProject
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by fcenedes** [comment]
What is you docker daemon configuration, version, and host running OS ?
have you try to connect thru the socket ? /var/run/docker.sock.
is your daemon running with tls mode like : 

dockerd -D --tls=true --tlscert=<your lovely cert pem file> --tlskey=<your lovely serverkey pem file> -H tcp://0.0.0.0:2376  ? (-D is for Debug)
what is the content of you daemon.json ?

**Comment by SonaliDasgupta** [comment]
To use docker without TLS, please use the following command to start the Docker daemon:

dockerd -H tcp://0.0.0.0:2375 

This causes the daemon to listen at port 2375 , which is a non-TLS port , and hence you shall not need any certificates to be configured while running the docker build maven goal.

**Comment by SonaliDasgupta** [comment]
While configuring docker properties in the POM Generation UI , the port 2375 should be specified in place of the default port 2376 , if the docker daemon is started without TLS.
