### ISSUE TITLE
fabric8:apply failing with Permission Error: Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://104.197.231.184/. Message: Forbidden! User null doesn't have permission

### ISSUE THREAD

**Issue by jmhenley5326** [TIBCOSoftware/bw6-plugin-maven#90]
Maven Plugin version: 1.2.2

Maven version: 3.3.9

Product : TIBCO Businessworks Container edition 

Product version: 2.2.1

Component: Maven build plugin

**Steps to reproduce the issue:**
1. Create basic application with docker properties and k8s properties
2. Set up Google Cloud Platform and establish auth tokens with gcloud auth login and gcloud auth application-default login and configure environment with gcloud config set commands
3. Setup docker login for google repository: docker login -u _token -p "$(gcloud auth print-access-token)" https://gcr.io
4. Create kube config: gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project jmh-project

**Additional environment details if any:**
Running from Jenkins pipeline but I have regressed back to running the Maven commands from the command line to ensure there are no issues. I get the same errors running on the Jenkins box from the command line as the jenkins user as I do running in the Jenkins Pipeline as well as running locally on my box with all the same configurations

**Describe the results you received:**
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.102:apply (default-cli) on project DevOpsSample: Failure executing: GET at: https://104.197.231.184/. Message: Forbidden! User null doesn't have permission.. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.102:apply (default-cli) on project DevOpsSample: Failure executing: GET at: https://104.197.231.184/. Message: Forbidden! User null doesn't have permission..
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failure executing: GET at: https://104.197.231.184/. Message: Forbidden! User null doesn't have permission..
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:251)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://104.197.231.184/. Message: Forbidden! User null doesn't have permission..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:290)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:212)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getRootPaths(BaseOperation.java:133)
	at io.fabric8.kubernetes.client.BaseClient.rootPaths(BaseClient.java:141)
	at io.fabric8.kubernetes.api.KubernetesHelper.isOpenShift(KubernetesHelper.java:1958)
	at io.fabric8.maven.ApplyMojo.execute(ApplyMojo.java:190)
	... 22 more

**Describe the results you expected:**
NOT an error.

**Additional information you deem important (e.g. issue happens only occasionally):**
jenkins@ip-172-31-45-111:~$ gcloud version
Google Cloud SDK 158.0.0
alpha 2017.06.02
beta 2017.06.02
bq 2.0.24
core 2017.06.02
gcloud 
gsutil 4.26

jenkins@ip-172-31-45-111:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fcenedes** [comment]
update the pom file of your application to have the fabric8 maven plugin to 2.2.215 version.
then retry the goal apply.
from k8s 1.6+, the kubernetes client has changed.

**Comment by fcenedes** [comment]
This apply to the BW6 plugin 1.2.2 and earlier

**Comment by fcenedes** [comment]
Issue to be close with the future version of the plugin, stay tuned !

**Comment by rahulagarwalcts** [comment]
Looks like this issues still exists with BW6 plugin 1.3.1 , I have bw plugin 1.3.1 but I was able to deploy this only after updating the all pom files.

**Comment by SonaliDasgupta** [comment]
Closing as resolved with Release 2.0.1 . Please reopen incase of queries.
